export type AiGenerationMode = "live_openai_only" | "openai_with_fallback" | "fallback_only";
export type GenerationSource = "openai" | "fallback" | "repair" | "mock";
export type GenerationProvider = "openai" | "local";
export type ValidationStatus = "passed" | "failed" | "repaired";
export type KeySource = "database" | "environment" | "none";

export type GenerationMetadata = {
  generationSource: GenerationSource;
  provider: GenerationProvider;
  model: string;
  usedFallback: boolean;
  fallbackReason: string | null;
  validationStatus: ValidationStatus;
  keySource: KeySource;
  openAiAttempted: boolean;
  openAiSucceeded: boolean;
  aiMode: AiGenerationMode;
};

const AI_MODES: AiGenerationMode[] = ["live_openai_only", "openai_with_fallback", "fallback_only"];

export function parseAiGenerationMode(input: unknown): AiGenerationMode {
  const value = String(input ?? "").trim().toLowerCase();
  if (AI_MODES.includes(value as AiGenerationMode)) {
    return value as AiGenerationMode;
  }

  // Accept label-like and separator-variant payloads from UI clients.
  const compact = value.replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  if (compact === "openai_with_fallback" || compact === "open_ai_with_fallback") {
    return "openai_with_fallback";
  }
  if (compact === "fallback_only" || compact === "fallback_only_testing") {
    return "fallback_only";
  }
  if (compact === "live_openai_only" || compact === "live_open_ai_only") {
    return "live_openai_only";
  }

  if (value.includes("fallback") && value.includes("openai")) {
    return "openai_with_fallback";
  }
  if (value.includes("fallback") && !value.includes("openai")) {
    return "fallback_only";
  }
  if (value.includes("live") && value.includes("openai")) {
    return "live_openai_only";
  }

  return "live_openai_only";
}

export function isFallbackAllowed(mode: AiGenerationMode): boolean {
  return mode === "openai_with_fallback" || mode === "fallback_only";
}

export function toValidationStatus(validation: unknown): ValidationStatus {
  if (validation && typeof validation === "object") {
    const row = validation as Record<string, unknown>;
    if (row.valid === false) return "failed";
    if (row.repaired === true) return "repaired";
  }
  return "passed";
}

export function buildGenerationMetadata(input: {
  aiMode: AiGenerationMode;
  generationSource: GenerationSource;
  provider: GenerationProvider;
  model: string;
  fallbackReason?: string | null;
  validation: unknown;
  keySource: KeySource;
  openAiAttempted: boolean;
  openAiSucceeded: boolean;
}): GenerationMetadata {
  return {
    aiMode: input.aiMode,
    generationSource: input.generationSource,
    provider: input.provider,
    model: input.model,
    usedFallback: input.generationSource === "fallback" || input.provider === "local",
    fallbackReason: input.fallbackReason ?? null,
    validationStatus: toValidationStatus(input.validation),
    keySource: input.keySource,
    openAiAttempted: input.openAiAttempted,
    openAiSucceeded: input.openAiSucceeded,
  };
}

export function generationDisplayLabel(meta: Pick<GenerationMetadata, "generationSource"> | null | undefined): "Generated by OpenAI" | "Generated by fallback" | null {
  if (!meta) return null;
  if (meta.generationSource === "fallback") return "Generated by fallback";
  if (meta.generationSource === "openai" || meta.generationSource === "repair") return "Generated by OpenAI";
  return null;
}
