export const adminNavItems = [
  { title: "Dashboard", href: "/admin", icon: "D" },
  { title: "Parents", href: "/admin/parents", icon: "P" },
  { title: "Students", href: "/admin/students", icon: "S" },
  { title: "Schools", href: "/admin/schools", icon: "SC" },
  { title: "Dictionary / Word Bank", href: "/admin/dictionary", icon: "DW" },
  { title: "Knowledge Graph", href: "/admin/knowledge-graph", icon: "KG" },
  { title: "Recovery Governance", href: "/admin/recovery-governance", icon: "RG" },
  { title: "AI Generator", href: "/admin/ai", icon: "AI" },
  { title: "Content Library", href: "/admin/content-library", icon: "CL" },
  { title: "Assignments", href: "/admin/assignments", icon: "AS" },
  { title: "Lessons", href: "/admin/lessons", icon: "L" },
  { title: "Rewards", href: "/admin/rewards", icon: "R" },
  { title: "Store / Shop", href: "/admin/store", icon: "SH" },
  { title: "Subscriptions", href: "/admin/subscriptions", icon: "B" },
  { title: "Trial Leads", href: "/admin/trial-leads", icon: "TL" },
  { title: "Pricing", href: "/admin/pricing", icon: "PR" },
  { title: "Reports", href: "/admin/reports", icon: "RP" },
  { title: "Support", href: "/admin/support", icon: "T" },
  { title: "Notifications", href: "/admin/notifications", icon: "N" },
  { title: "Messages", href: "/admin/messages", icon: "MS" },
  { title: "Voice & Media", href: "/admin/voice-media", icon: "VM" },
  { title: "Inbox", href: "/admin/inbox", icon: "✉" },
  { title: "TrueNumeris", href: "/admin/integrations/truenumeris", icon: "TN" },
  { title: "Branding", href: "/admin/branding", icon: "BR" },
  { title: "Audit Logs", href: "/admin/audit-logs", icon: "A" },
  { title: "Settings", href: "/admin/settings", icon: "G" },
] as const;
