export const GA_ALPHABET = [
  ["A", "a"],
  ["B", "b"],
  ["D", "d"],
  ["E", "e"],
  ["Ɛ", "ɛ"],
  ["F", "f"],
  ["G", "g"],
  ["H", "h"],
  ["I", "i"],
  ["J", "j"],
  ["K", "k"],
  ["L", "l"],
  ["M", "m"],
  ["N", "n"],
  ["Ŋ", "ŋ"],
  ["O", "o"],
  ["Ɔ", "ɔ"],
  ["P", "p"],
  ["R", "r"],
  ["S", "s"],
  ["T", "t"],
  ["U", "u"],
  ["V", "v"],
  ["W", "w"],
  ["Y", "y"],
  ["Z", "z"],
] as const;

export const GA_SPECIAL_LETTERS = ["Ɛ ɛ", "Ŋ ŋ", "Ɔ ɔ"] as const;

export const GA_VOWELS = ["a", "e", "ɛ", "i", "o", "ɔ", "u"] as const;

export const GA_NASAL_VOWELS = ["ã", "ẽ", "ɛ̃", "ĩ", "õ", "ɔ̃", "ũ"] as const;

export const GA_CONSONANTS_AND_CLUSTERS = [
  "b",
  "d",
  "f",
  "g",
  "gb",
  "gw",
  "h",
  "hw",
  "j",
  "jw",
  "k",
  "kp",
  "kw",
  "l",
  "m",
  "n",
  "ny",
  "ŋ",
  "ŋm",
  "ŋw",
  "p",
  "r",
  "s",
  "sh",
  "shw",
  "t",
  "ts",
  "tsw",
  "v",
  "w",
  "y",
  "z",
] as const;

export const GA_ALPHABET_BEGINNER_SECTIONS = [
  "Meet the Ga alphabet",
  "Special Ga letters",
  "Vowel sounds",
  "Nasal vowel sounds",
  "Consonant sounds",
  "Sound combinations",
  "Practice reading Ga words",
] as const;
