export const productionChecklist = [
  { area: "Provider credentials", item: "OpenAI, payment, email, voice and storage keys saved in Settings and tested." },
  { area: "Payments", item: "Webhook secret configured and checkout/subscription events verified." },
  { area: "Monitoring", item: "Error monitoring provider configured with alerts for API failures and failed jobs." },
  { area: "Backups", item: "Daily database backups enabled and restore tested." },
  { area: "Security", item: "Admin access, permissions, API key masking, subscription enforcement and audit logs verified." },
  { area: "School scoping", item: "School admin APIs never trust client schoolId; platform admin school tabs scoped by path id." },
  { area: "Portal routing", item: "Owner/admin land on /school-admin; teachers on /teacher; platform admin on /admin; dual-role switch does not elevate." },
  { area: "Short Learning", item: "Bookings, shifts, coverage, honesty acknowledgement, no cancel fees; human support only when on-shift available." },
  { area: "Day School", item: "Timetable, live classroom, attendance remain separate from Short Learning bookings." },
  { area: "Human support", item: "Queue only with eligible tutor capacity; AI continues when none; shift grace blocks new assigns." },
  { area: "Public website", item: "UK home, Features, Short Learning, FAQ, policy footer links, canonical /auth/login." },
  { area: "Student portal", item: "Day School Today and Short Learning nav; dedicated Short Learning learn path without daytime attendance merge." },
  { area: "Policies & knowledge", item: "Privacy, terms, cookies, safeguarding, retention, AI use, knowledge centre published and linked." },
  { area: "Cron / reminders", item: "Vercel Cron GET /api/cron/short-learning-reminders every 10 min (*/10 * * * *) with CRON_SECRET; Pro plan required for sub-daily." },
  { area: "Testing", item: "Parent sign up to child learning journey tested end to end; Short Learning + admin portal UAT evidence saved." },
  { area: "Compliance", item: "Parent consent, data deletion process and child data minimisation checked." },
  { area: "Launch flags", item: "LAUNCH_ENABLE_SCHOOL_PORTAL and related UK launch flags set for production; beta modules remain secondary." },
];
