export type SpellingWordBankEntry = {
  id: string;
  word: string;
  level: 1 | 2 | 3 | 4 | 5;
  hint: string;
  sentenceContext: string;
  categoryHint: string;
  syllables: string;
  emoji: string;
  promptType?: "voice" | "text" | "image";
  imageUrl?: string;
  patterns: string[];
};

function makeWord(
  level: 1 | 2 | 3 | 4 | 5,
  word: string,
  hint: string,
  categoryHint: string,
  syllables: string,
  emoji: string,
  patterns: string[],
  sentenceContext?: string,
  promptType?: "voice" | "text" | "image",
  imageUrl?: string,
): SpellingWordBankEntry {
  return {
    id: `spell-${level}-${word.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    word,
    level,
    hint,
    categoryHint,
    syllables,
    emoji,
    promptType,
    imageUrl,
    patterns,
    sentenceContext: sentenceContext ?? `Listen and spell the word. ${word}.`,
  };
}

const L1: SpellingWordBankEntry[] = [
  makeWord(1, "cat", "A small pet that says meow", "animal", "cat", "🐱", ["cvc"]),
  makeWord(1, "dog", "A pet that barks", "animal", "dog", "🐶", ["cvc"]),
  makeWord(1, "sun", "It shines in the sky", "nature", "sun", "☀️", ["cvc"]),
  makeWord(1, "hat", "You wear it on your head", "clothes", "hat", "🧢", ["cvc"]),
  makeWord(1, "bed", "You sleep on it", "home", "bed", "🛏️", ["cvc"]),
  makeWord(1, "pen", "You write with it", "school", "pen", "🖊️", ["cvc"]),
  makeWord(1, "cup", "You drink from it", "home", "cup", "🥤", ["cvc"]),
  makeWord(1, "map", "It helps you find places", "school", "map", "🗺️", ["cvc"]),
  makeWord(1, "pig", "A farm animal that oinks", "animal", "pig", "🐷", ["cvc"]),
  makeWord(1, "run", "Move fast on your feet", "action", "run", "🏃", ["cvc"]),
  makeWord(1, "sit", "Rest on a chair", "action", "sit", "🪑", ["cvc"]),
  makeWord(1, "box", "You put things inside it", "object", "box", "📦", ["cvc"]),
  makeWord(1, "bus", "A big vehicle for people", "vehicle", "bus", "🚌", ["cvc"]),
  makeWord(1, "fox", "A wild animal with a bushy tail", "animal", "fox", "🦊", ["cvc"]),
  makeWord(1, "jam", "Sweet fruit spread", "food", "jam", "🍓", ["cvc"]),
  makeWord(1, "bag", "You carry things in it", "object", "bag", "🎒", ["cvc"]),
  makeWord(1, "van", "A vehicle bigger than a car", "vehicle", "van", "🚐", ["cvc"]),
  makeWord(1, "lid", "The top of a box or cup", "object", "lid", "🥫", ["cvc"]),
  makeWord(1, "log", "A piece of wood", "nature", "log", "🪵", ["cvc"]),
  makeWord(1, "mud", "Wet soil", "nature", "mud", "🕳️", ["cvc"], undefined, "image", "/spelling-icons/mud.svg"),
  makeWord(1, "net", "Used to catch things", "object", "net", "🥅", ["cvc"]),
  makeWord(1, "pot", "Used for cooking", "home", "pot", "🍲", ["cvc"]),
  makeWord(1, "red", "A bright colour", "colour", "red", "🔴", ["cvc"]),
  makeWord(1, "toy", "Something children play with", "play", "toy", "🧸", ["cvc"]),
  makeWord(1, "egg", "Food from a hen", "food", "egg", "🥚", ["double_letter"]),
  // More Level 1 — short simple words
  makeWord(1, "ant", "A tiny insect", "animal", "ant", "🐜", ["cvc"]),
  makeWord(1, "bat", "An animal that flies at night", "animal", "bat", "🦇", ["cvc"]),
  makeWord(1, "bug", "A small insect", "animal", "bug", "🐛", ["cvc"]),
  makeWord(1, "cot", "A small bed for a baby", "home", "cot", "🛏️", ["cvc"]),
  makeWord(1, "den", "A cosy hiding place", "home", "den", "🏕️", ["cvc"]),
  makeWord(1, "dip", "Put briefly into liquid", "action", "dip", "🫕", ["cvc"]),
  makeWord(1, "dot", "A small round mark", "school", "dot", "🔴", ["cvc"]),
  makeWord(1, "fan", "It blows cool air", "home", "fan", "🪭", ["cvc"]),
  makeWord(1, "fit", "Healthy and active", "description", "fit", "💪", ["cvc"]),
  makeWord(1, "gap", "A space between two things", "description", "gap", "🕳️", ["cvc"]),
  makeWord(1, "gem", "A shiny precious stone", "object", "gem", "💎", ["cvc"]),
  makeWord(1, "hip", "Part of your body at the side", "body", "hip", "🧍", ["cvc"]),
  makeWord(1, "hop", "Jump on one foot", "action", "hop", "🐸", ["cvc"]),
  makeWord(1, "hug", "Wrap your arms around someone", "action", "hug", "🤗", ["cvc"]),
  makeWord(1, "jet", "A fast plane", "vehicle", "jet", "✈️", ["cvc"]),
  makeWord(1, "jug", "A container for pouring", "home", "jug", "🫙", ["cvc"]),
  makeWord(1, "lab", "A science room", "school", "lab", "🔬", ["cvc"]),
  makeWord(1, "leg", "Part of your body you walk on", "body", "leg", "🦵", ["cvc"]),
  makeWord(1, "mix", "Stir things together", "action", "mix", "🥣", ["cvc"]),
  makeWord(1, "mop", "Used to clean the floor", "home", "mop", "🧹", ["cvc"]),
  makeWord(1, "nap", "A short sleep", "action", "nap", "😴", ["cvc"]),
  makeWord(1, "nod", "Move your head up and down", "action", "nod", "🙇", ["cvc"]),
  makeWord(1, "nut", "A hard crunchy snack", "food", "nut", "🥜", ["cvc"]),
  makeWord(1, "pan", "Used for cooking on the hob", "home", "pan", "🍳", ["cvc"]),
  makeWord(1, "pat", "Touch gently", "action", "pat", "🤚", ["cvc"]),
  makeWord(1, "pin", "A sharp pointed object", "object", "pin", "📌", ["cvc"]),
  makeWord(1, "pit", "A deep hole in the ground", "nature", "pit", "🕳️", ["cvc"]),
  makeWord(1, "rag", "An old piece of cloth", "object", "rag", "🧻", ["cvc"]),
  makeWord(1, "ram", "A male sheep", "animal", "ram", "🐏", ["cvc"]),
  makeWord(1, "rip", "Tear something apart", "action", "rip", "✂️", ["cvc"]),
  makeWord(1, "rob", "Take something that is not yours", "action", "rob", "🦹", ["cvc"]),
  makeWord(1, "rot", "Go bad or decay", "nature", "rot", "🦠", ["cvc"]),
  makeWord(1, "rub", "Move back and forth", "action", "rub", "💆", ["cvc"]),
  makeWord(1, "rug", "A mat on the floor", "home", "rug", "🧶", ["cvc"], undefined, "image", "/spelling-icons/rug.svg"),
  makeWord(1, "sap", "Liquid inside a tree", "nature", "sap", "🌳", ["cvc"]),
  makeWord(1, "set", "Put something in place", "action", "set", "📥", ["cvc"]),
  makeWord(1, "six", "The number after five", "number", "six", "6️⃣", ["cvc"]),
  makeWord(1, "sob", "Cry loudly", "feeling", "sob", "😢", ["cvc"]),
  makeWord(1, "tap", "Turn it on for water", "home", "tap", "🚰", ["cvc"]),
  makeWord(1, "tip", "The pointed end of something", "description", "tip", "📍", ["cvc"]),
  makeWord(1, "top", "The highest part", "position", "top", "🔝", ["cvc"]),
  makeWord(1, "tub", "A big bowl for bathing", "home", "tub", "🛁", ["cvc"]),
  makeWord(1, "tug", "Pull hard", "action", "tug", "💪", ["cvc"]),
  makeWord(1, "web", "A spider makes this", "animal", "web", "🕸️", ["cvc"]),
  makeWord(1, "wet", "Covered in water", "description", "wet", "💧", ["cvc"]),
  makeWord(1, "win", "Come first in a game", "action", "win", "🏆", ["cvc"]),
  makeWord(1, "zip", "A fastener on a bag or coat", "clothes", "zip", "🤐", ["cvc"]),
];

const L2: SpellingWordBankEntry[] = [
  makeWord(2, "ship", "A boat on the sea", "transport", "ship", "🚢", ["sh"]),
  makeWord(2, "shop", "A place to buy things", "place", "shop", "🏪", ["sh"]),
  makeWord(2, "fish", "An animal that swims", "animal", "fish", "🐟", ["sh"]),
  makeWord(2, "shell", "Found on the beach", "nature", "shell", "🐚", ["sh", "double_letter"]),
  makeWord(2, "chair", "You sit on it", "home", "chair", "🪑", ["ch"]),
  makeWord(2, "chip", "A crunchy snack", "food", "chip", "🍟", ["ch"]),
  makeWord(2, "chop", "Cut into pieces", "action", "chop", "🔪", ["ch"]),
  makeWord(2, "chicken", "A farm bird", "animal", "chick-en", "🐔", ["ch", "ck"]),
  makeWord(2, "thin", "Not thick", "description", "thin", "🧵", ["th"]),
  makeWord(2, "three", "The number after two", "number", "three", "3️⃣", ["th"]),
  makeWord(2, "thumb", "Part of your hand", "body", "thumb", "👍", ["th"]),
  makeWord(2, "bath", "You wash in it", "home", "bath", "🛁", ["th"]),
  makeWord(2, "think", "Use your mind", "action", "think", "🧠", ["th"]),
  makeWord(2, "frog", "A small animal that jumps", "animal", "frog", "🐸", ["blend"]),
  makeWord(2, "flag", "A symbol for a country", "object", "flag", "🚩", ["blend"]),
  makeWord(2, "clap", "Hit hands together", "action", "clap", "👏", ["blend"]),
  makeWord(2, "drum", "A musical instrument", "music", "drum", "🥁", ["blend"]),
  makeWord(2, "grass", "Green plants on the ground", "nature", "grass", "🌱", ["double_letter"]),
  makeWord(2, "clock", "It tells the time", "object", "clock", "🕒", ["ck_end"]),
  makeWord(2, "black", "A dark colour", "colour", "black", "⚫", ["ck_end"]),
  makeWord(2, "quick", "Very fast", "description", "quick", "⚡", ["ck_end"]),
  makeWord(2, "school", "A place where children learn", "place", "school", "🏫", ["sch", "double_letter"]),
  makeWord(2, "garden", "A place where plants grow", "nature", "gar-den", "🌻", ["core"]),
  makeWord(2, "rabbit", "An animal with long ears", "animal", "rab-bit", "🐰", ["double_letter"]),
  makeWord(2, "window", "You look through it", "home", "win-dow", "🪟", ["core"]),
  // More Level 2 — digraphs, blends, CCVC/CVCC
  makeWord(2, "shed", "A small building in a garden", "home", "shed", "🏚️", ["sh"]),
  makeWord(2, "shelf", "A board on a wall to store things", "home", "shelf", "📚", ["sh", "blend"]),
  makeWord(2, "shirt", "You wear it on your top half", "clothes", "shirt", "👕", ["sh"]),
  makeWord(2, "shoot", "Send something forward fast", "action", "shoot", "🎯", ["sh", "double_letter"]),
  makeWord(2, "shark", "A large sea fish", "animal", "shark", "🦈", ["sh"]),
  makeWord(2, "shadow", "A dark shape behind you in sunlight", "nature", "sha-dow", "🌑", ["sh"]),
  makeWord(2, "check", "Look at carefully", "action", "check", "✔️", ["ch", "ck_end"]),
  makeWord(2, "chest", "A box for storing things", "object", "chest", "📦", ["ch", "blend"]),
  makeWord(2, "chain", "Linked metal rings", "object", "chain", "⛓️", ["ch"]),
  makeWord(2, "cheek", "The soft side of your face", "body", "cheek", "😊", ["ch", "double_letter"]),
  makeWord(2, "cheese", "A dairy food", "food", "cheese", "🧀", ["ch", "double_letter"]),
  makeWord(2, "those", "Plural of that", "school", "those", "🫵", ["th"], undefined, "image", "/spelling-icons/those.svg"),
  makeWord(2, "thank", "Show you are grateful", "action", "thank", "🙏", ["th"]),
  makeWord(2, "thick", "Wide and solid", "description", "thick", "📏", ["th", "ck_end"]),
  makeWord(2, "thief", "Someone who steals", "people", "thief", "🕵️", ["th"]),
  makeWord(2, "thorn", "A sharp point on a plant", "nature", "thorn", "🌹", ["th"]),
  makeWord(2, "blend", "Mix together smoothly", "action", "blend", "🥤", ["blend"]),
  makeWord(2, "brave", "Not afraid", "feeling", "brave", "🦁", ["blend"]),
  makeWord(2, "brick", "A block used to build walls", "object", "brick", "🧱", ["blend", "ck_end"]),
  makeWord(2, "crack", "A thin break in something", "object", "crack", "💥", ["blend", "ck_end"]),
  makeWord(2, "crab", "A sea creature with claws", "animal", "crab", "🦀", ["blend"]),
  makeWord(2, "crisp", "Thin crunchy snack", "food", "crisp", "🥔", ["blend"]),
  makeWord(2, "drip", "A drop of liquid falling", "nature", "drip", "💧", ["blend"]),
  makeWord(2, "drop", "A small amount of liquid", "nature", "drop", "🫧", ["blend"]),
  makeWord(2, "flap", "Move up and down", "action", "flap", "🦋", ["blend"]),
  makeWord(2, "flat", "Smooth with no bumps", "description", "flat", "⬜", ["blend"]),
  makeWord(2, "flip", "Turn over quickly", "action", "flip", "🔄", ["blend"]),
  makeWord(2, "flow", "Move along smoothly", "nature", "flow", "🌊", ["blend"]),
  makeWord(2, "glue", "Sticky liquid used to join things", "object", "glue", "🧴", ["blend"]),
  makeWord(2, "glow", "Shine with soft light", "nature", "glow", "✨", ["blend"]),
  makeWord(2, "grab", "Take hold of something quickly", "action", "grab", "🤲", ["blend"]),
  makeWord(2, "grid", "A pattern of squares", "school", "grid", "🔲", ["blend"]),
  makeWord(2, "grin", "Smile broadly", "action", "grin", "😁", ["blend"]),
  makeWord(2, "plan", "Work out what to do", "action", "plan", "📋", ["blend"]),
  makeWord(2, "plant", "Something green that grows", "nature", "plant", "🌱", ["blend"]),
  makeWord(2, "plum", "A purple fruit", "food", "plum", "🟣", ["blend"], undefined, "image", "/spelling-icons/plum.svg"),
  makeWord(2, "press", "Push down firmly", "action", "press", "🖱️", ["blend", "double_letter"]),
  makeWord(2, "price", "How much something costs", "object", "price", "💰", ["blend"]),
  makeWord(2, "print", "Write or copy clearly", "school", "print", "🖨️", ["blend"]),
  makeWord(2, "proud", "Feeling good about yourself", "feeling", "proud", "😤", ["blend"]),
  makeWord(2, "slam", "Close something hard and fast", "action", "slam", "💥", ["blend"]),
  makeWord(2, "sled", "A vehicle that slides on snow", "vehicle", "sled", "🛷", ["blend"]),
  makeWord(2, "slip", "Slide by accident", "action", "slip", "🫤", ["blend"]),
  makeWord(2, "slug", "A slimy garden creature", "animal", "slug", "🐌", ["blend"]),
  makeWord(2, "smell", "Use your nose to sense", "action", "smell", "👃", ["blend", "double_letter"]),
  makeWord(2, "smile", "Happy expression", "feeling", "smile", "😊", ["blend", "silent_e"]),
  makeWord(2, "smoke", "Grey cloud from fire", "nature", "smoke", "🔥", ["blend", "silent_e"]),
  makeWord(2, "snap", "Break with a sharp sound", "action", "snap", "✂️", ["blend"]),
  makeWord(2, "snail", "A slow creature with a shell", "animal", "snail", "🐌", ["blend"]),
  makeWord(2, "snake", "A long reptile without legs", "animal", "snake", "🐍", ["blend", "silent_e"]),
  makeWord(2, "snow", "White frozen rain", "weather", "snow", "❄️", ["blend"]),
  makeWord(2, "speak", "Use your voice to talk", "action", "speak", "🗣️", ["blend"]),
  makeWord(2, "spend", "Use money or time", "action", "spend", "💸", ["blend"]),
  makeWord(2, "spill", "Let liquid fall by accident", "action", "spill", "💦", ["blend", "double_letter"]),
  makeWord(2, "spin", "Turn round and round", "action", "spin", "🌀", ["blend"]),
  makeWord(2, "spot", "Notice something", "action", "spot", "🔍", ["blend"]),
  makeWord(2, "spring", "Season after winter", "time", "spring", "🌸", ["blend"]),
  makeWord(2, "sprint", "Run very fast", "action", "sprint", "🏃", ["blend"]),
  makeWord(2, "stamp", "Press a pattern onto paper", "action", "stamp", "📮", ["blend"]),
  makeWord(2, "stand", "Be upright on your feet", "action", "stand", "🧍", ["blend"]),
  makeWord(2, "star", "A shiny object in the night sky", "nature", "star", "⭐", ["blend"]),
  makeWord(2, "step", "Move one foot forward", "action", "step", "👣", ["blend"]),
  makeWord(2, "stick", "A thin piece of wood", "nature", "stick", "🪵", ["blend", "ck_end"]),
  makeWord(2, "sting", "A sharp pain from an insect", "animal", "sting", "🐝", ["blend"]),
  makeWord(2, "stock", "A supply of something", "object", "stock", "📦", ["blend", "ck_end"]),
  makeWord(2, "stone", "A small rock", "nature", "stone", "🪨", ["blend", "silent_e"]),
  makeWord(2, "stop", "Come to a halt", "action", "stop", "🛑", ["blend"]),
  makeWord(2, "storm", "Bad weather with thunder and rain", "weather", "storm", "⛈️", ["blend"]),
  makeWord(2, "strap", "A long thin strip", "object", "strap", "👜", ["blend"]),
  makeWord(2, "street", "A road in a town", "place", "street", "🏙️", ["blend", "double_letter"]),
  makeWord(2, "strong", "Powerful", "description", "strong", "💪", ["blend"]),
  makeWord(2, "stuck", "Cannot move", "description", "stuck", "😬", ["blend", "ck_end"]),
  makeWord(2, "swim", "Move through water", "action", "swim", "🏊", ["blend"]),
  makeWord(2, "swing", "Move back and forth", "action", "swing", "🪂", ["blend"]),
  makeWord(2, "track", "A path or mark left behind", "nature", "track", "🛤️", ["blend", "ck_end"]),
  makeWord(2, "trap", "Catch something", "action", "trap", "🪤", ["blend"]),
  makeWord(2, "tree", "A tall plant with a trunk", "nature", "tree", "🌳", ["blend", "double_letter"]),
  makeWord(2, "trick", "Something clever but tricky", "play", "trick", "🃏", ["blend", "ck_end"]),
  makeWord(2, "trip", "A journey", "action", "trip", "✈️", ["blend"]),
  makeWord(2, "truck", "A large vehicle", "vehicle", "truck", "🚛", ["blend", "ck_end"]),
  makeWord(2, "trunk", "A big suitcase or a tree part", "object", "trunk", "🪵", ["blend"]),
  makeWord(2, "trust", "Believe in someone", "feeling", "trust", "🤝", ["blend"]),
  makeWord(2, "twist", "Turn and wind together", "action", "twist", "🌀", ["blend"]),
];

const L3: SpellingWordBankEntry[] = [
  makeWord(3, "cake", "A sweet treat", "food", "cake", "🎂", ["silent_e"]),
  makeWord(3, "bike", "You ride it with pedals", "transport", "bike", "🚲", ["silent_e"]),
  makeWord(3, "home", "Where you live", "home", "home", "🏠", ["silent_e"]),
  makeWord(3, "make", "To create something", "action", "make", "🛠️", ["silent_e"]),
  makeWord(3, "time", "Clock measurement", "time", "time", "⏰", ["silent_e"]),
  makeWord(3, "ride", "To travel on something", "action", "ride", "🚲", ["silent_e"]),
  makeWord(3, "hope", "A wish for something", "feeling", "hope", "🌈", ["silent_e"]),
  makeWord(3, "name", "What people call you", "people", "name", "🏷️", ["silent_e"]),
  makeWord(3, "note", "A short message", "school", "note", "📝", ["silent_e"]),
  makeWord(3, "cute", "Very pretty or adorable", "description", "cute", "🥰", ["silent_e"]),
  makeWord(3, "stone", "A small rock", "nature", "stone", "🪨", ["silent_e"]),
  makeWord(3, "shine", "Give out light", "nature", "shine", "✨", ["sh", "silent_e"]),
  makeWord(3, "whale", "A very large sea animal", "animal", "whale", "🐋", ["silent_e"]),
  makeWord(3, "brave", "Not afraid", "feeling", "brave", "🦁", ["silent_e"]),
  makeWord(3, "plate", "You eat food from it", "home", "plate", "🍽️", ["silent_e"]),
  makeWord(3, "drive", "Control a car", "action", "drive", "🚗", ["silent_e"]),
  makeWord(3, "space", "The area beyond Earth", "science", "space", "🚀", ["silent_e"]),
  makeWord(3, "those", "More than one of that", "school", "those", "🫵", ["th", "silent_e"], undefined, "image", "/spelling-icons/those.svg"),
  makeWord(3, "inside", "The inner part", "position", "in-side", "📦", ["silent_e"]),
  makeWord(3, "outside", "The outer part", "position", "out-side", "🌳", ["silent_e"]),
  makeWord(3, "because", "Gives a reason", "school", "be-cause", "💬", ["core"]),
  makeWord(3, "before", "Earlier than now", "time", "be-fore", "⏮️", ["core"]),
  makeWord(3, "under", "Below something", "position", "un-der", "⬇️", ["core"]),
  makeWord(3, "river", "Water that flows", "nature", "ri-ver", "🏞️", ["core"]),
  makeWord(3, "forest", "A place with many trees", "nature", "for-est", "🌲", ["core"]),
  // Compound words — two clear words joined
  makeWord(3, "rainbow", "Colourful arch after rain", "nature", "rain-bow", "🌈", ["compound"]),
  makeWord(3, "sunshine", "Bright light from the sun", "nature", "sun-shine", "☀️", ["compound"]),
  makeWord(3, "bedroom", "A room where you sleep", "home", "bed-room", "🛏️", ["compound"]),
  makeWord(3, "football", "A sport played with a round ball", "sport", "foot-ball", "⚽", ["compound"]),
  makeWord(3, "birthday", "The day you were born", "celebration", "birth-day", "🎂", ["compound"]),
  makeWord(3, "notebook", "A book you write in", "school", "note-book", "📓", ["compound"]),
  makeWord(3, "cupcake", "A small sweet cake", "food", "cup-cake", "🧁", ["compound"]),
  makeWord(3, "playground", "A place to play outside", "place", "play-ground", "🛝", ["compound"]),
  makeWord(3, "doorbell", "A button that rings a bell", "home", "door-bell", "🔔", ["compound"]),
  makeWord(3, "starfish", "A sea animal shaped like a star", "animal", "star-fish", "⭐", ["compound"]),
  makeWord(3, "snowflake", "A tiny piece of snow", "weather", "snow-flake", "❄️", ["compound"]),
  makeWord(3, "classroom", "A room in school for lessons", "school", "class-room", "🏫", ["compound"]),
  // More Level 3 — silent-e extensions, vowel digraphs, common longer words
  makeWord(3, "alike", "The same as each other", "description", "a-like", "👯", ["silent_e"]),
  makeWord(3, "alone", "By yourself", "feeling", "a-lone", "🧍", ["silent_e"]),
  makeWord(3, "awake", "Not asleep", "description", "a-wake", "👁️", ["silent_e"]),
  makeWord(3, "blame", "Say someone caused something bad", "action", "blame", "😠", ["silent_e"]),
  makeWord(3, "blaze", "A big bright fire", "nature", "blaze", "🔥", ["silent_e"]),
  makeWord(3, "bride", "A woman getting married", "people", "bride", "👰", ["silent_e"]),
  makeWord(3, "broke", "Snapped into pieces", "action", "broke", "💔", ["silent_e"]),
  makeWord(3, "chose", "Picked one thing over another", "action", "chose", "☑️", ["silent_e"]),
  makeWord(3, "close", "Near, or to shut", "position", "close", "🚪", ["silent_e"]),
  makeWord(3, "crane", "A tall machine or a bird", "object", "crane", "🏗️", ["silent_e"]),
  makeWord(3, "crate", "A wooden box for carrying things", "object", "crate", "📦", ["silent_e"]),
  makeWord(3, "flame", "A tongue of fire", "nature", "flame", "🔥", ["silent_e"]),
  makeWord(3, "flute", "A musical instrument", "music", "flute", "🪈", ["silent_e"]),
  makeWord(3, "froze", "Turned to ice", "nature", "froze", "🧊", ["silent_e"]),
  makeWord(3, "gave", "Passed something to someone", "action", "gave", "🎁", ["silent_e"]),
  makeWord(3, "glide", "Move smoothly through the air", "action", "glide", "🦅", ["silent_e"]),
  makeWord(3, "globe", "A round model of the Earth", "school", "globe", "🌍", ["silent_e"]),
  makeWord(3, "grade", "A level or mark in school", "school", "grade", "📊", ["silent_e"]),
  makeWord(3, "grape", "A small round fruit", "food", "grape", "🍇", ["silent_e"]),
  makeWord(3, "graze", "Eat grass", "action", "graze", "🐄", ["silent_e"]),
  makeWord(3, "gripe", "Complain about something", "action", "gripe", "😤", ["silent_e"]),
  makeWord(3, "grove", "A small group of trees", "nature", "grove", "🌳", ["silent_e"]),
  makeWord(3, "invite", "Ask someone to come", "action", "in-vite", "📨", ["silent_e"]),
  makeWord(3, "large", "Big in size", "description", "large", "🐘", ["silent_e"]),
  makeWord(3, "lemon", "A sour yellow fruit", "food", "lem-on", "🍋", ["core"]),
  makeWord(3, "mango", "A tropical orange fruit", "food", "man-go", "🥭", ["core"]),
  makeWord(3, "maybe", "Possibly", "description", "may-be", "🤔", ["silent_e"]),
  makeWord(3, "nurse", "Someone who cares for patients", "people", "nurse", "👩‍⚕️", ["silent_e"]),
  makeWord(3, "orange", "A round citrus fruit", "food", "or-ange", "🍊", ["silent_e"]),
  makeWord(3, "palace", "A grand building for royalty", "place", "pal-ace", "🏰", ["silent_e"]),
  makeWord(3, "pause", "Stop briefly", "action", "pause", "⏸️", ["silent_e"]),
  makeWord(3, "phase", "A stage in a process", "school", "phase", "🌙", ["silent_e"], undefined, "image", "/spelling-icons/phase.svg"),
  makeWord(3, "phone", "You call people with it", "technology", "phone", "📱", ["silent_e"]),
  makeWord(3, "place", "A location or spot", "position", "place", "📍", ["silent_e"]),
  makeWord(3, "plane", "An aircraft", "vehicle", "plane", "✈️", ["silent_e"]),
  makeWord(3, "please", "Be polite when asking", "action", "please", "🙏", ["silent_e"]),
  makeWord(3, "price", "Amount you pay", "object", "price", "💰", ["silent_e"]),
  makeWord(3, "prince", "Son of a king or queen", "people", "prince", "🤴", ["silent_e"]),
  makeWord(3, "quite", "Rather or completely", "description", "quite", "✅", ["silent_e"]),
  makeWord(3, "quote", "Words said by someone", "school", "quote", "💬", ["silent_e"]),
  makeWord(3, "race", "A competition of speed", "sport", "race", "🏁", ["silent_e"]),
  makeWord(3, "raise", "Lift something up", "action", "raise", "⬆️", ["silent_e"]),
  makeWord(3, "range", "A spread from one thing to another", "school", "range", "📏", ["silent_e"], undefined, "image", "/spelling-icons/range.svg"),
  makeWord(3, "rate", "Speed or frequency of something", "school", "rate", "⏱️", ["silent_e"]),
  makeWord(3, "safe", "Not in danger", "description", "safe", "🛡️", ["silent_e"]),
  makeWord(3, "scale", "Used to weigh things", "object", "scale", "⚖️", ["silent_e"]),
  makeWord(3, "scene", "A view or part of a film", "school", "scene", "🎬", ["silent_e"]),
  makeWord(3, "score", "Points in a game", "sport", "score", "🏆", ["silent_e"]),
  makeWord(3, "sense", "One of the five senses", "body", "sense", "👁️", ["silent_e"]),
  makeWord(3, "serve", "Give food or help to someone", "action", "serve", "🍽️", ["silent_e"]),
  makeWord(3, "shade", "An area out of direct sunlight", "nature", "shade", "🌥️", ["silent_e"]),
  makeWord(3, "shake", "Move quickly back and forth", "action", "shake", "🫨", ["silent_e"]),
  makeWord(3, "shame", "A feeling of embarrassment", "feeling", "shame", "😳", ["silent_e"]),
  makeWord(3, "shape", "The outline of something", "school", "shape", "🔷", ["silent_e"]),
  makeWord(3, "share", "Give part of something to others", "action", "share", "🤝", ["silent_e"]),
  makeWord(3, "skate", "Glide on ice or wheels", "sport", "skate", "⛸️", ["silent_e"]),
  makeWord(3, "slave", "A person forced to work", "history", "slave", "⛓️", ["silent_e"]),
  makeWord(3, "slide", "Move smoothly downward", "action", "slide", "🛝", ["silent_e"]),
  makeWord(3, "slope", "Ground that goes upward or downward", "nature", "slope", "⛷️", ["silent_e"]),
  makeWord(3, "smoke", "Grey cloud from a fire", "nature", "smoke", "🔥", ["silent_e"]),
  makeWord(3, "solve", "Find the answer to a problem", "action", "solve", "✅", ["silent_e"]),
  makeWord(3, "spine", "Your backbone", "body", "spine", "🦴", ["silent_e"]),
  makeWord(3, "spoke", "Said something out loud", "action", "spoke", "🗣️", ["silent_e"]),
  makeWord(3, "spore", "A tiny seed from a plant", "science", "spore", "🍄", ["silent_e"]),
  makeWord(3, "stage", "A raised platform for performers", "place", "stage", "🎭", ["silent_e"]),
  makeWord(3, "stake", "A sharpened post driven into ground", "object", "stake", "🪵", ["silent_e"]),
  makeWord(3, "stale", "No longer fresh", "food", "stale", "🥖", ["silent_e"]),
  makeWord(3, "stare", "Look fixedly at something", "action", "stare", "👁️", ["silent_e"]),
  makeWord(3, "state", "A country or condition", "school", "state", "🗺️", ["silent_e"]),
  makeWord(3, "stove", "Appliance for cooking", "home", "stove", "🍳", ["silent_e"]),
  makeWord(3, "stripe", "A long band of colour", "description", "stripe", "🦓", ["silent_e"]),
  makeWord(3, "style", "A way of doing or looking", "description", "style", "✨", ["silent_e"]),
  makeWord(3, "swipe", "Slide your finger across a screen", "technology", "swipe", "📱", ["silent_e"]),
  makeWord(3, "table", "A piece of furniture", "home", "ta-ble", "🍽️", ["silent_e"], undefined, "image", "/spelling-icons/table.svg"),
  makeWord(3, "taste", "One of the five senses", "body", "taste", "👅", ["silent_e"]),
  makeWord(3, "theme", "The main idea", "school", "theme", "💡", ["silent_e"], undefined, "image", "/spelling-icons/theme.svg"),
  makeWord(3, "there", "In that place", "position", "there", "📍", ["silent_e"]),
  makeWord(3, "these", "More than one of this", "school", "these", "📚", ["silent_e"]),
  makeWord(3, "throne", "A special chair for a king or queen", "object", "throne", "👑", ["silent_e"]),
  makeWord(3, "trade", "Buy and sell goods", "school", "trade", "🏪", ["silent_e"]),
  makeWord(3, "trail", "A path through nature", "nature", "trail", "👣", ["silent_e"]),
  makeWord(3, "twice", "Two times", "number", "twice", "2️⃣", ["silent_e"]),
  makeWord(3, "uncle", "Your parent's brother", "family", "un-cle", "👨‍🦳", ["silent_e"]),
  makeWord(3, "unite", "Come together", "action", "u-nite", "🤝", ["silent_e"]),
  makeWord(3, "value", "How important or useful something is", "school", "val-ue", "💡", ["silent_e"]),
  makeWord(3, "verse", "A section of a poem or song", "school", "verse", "🎵", ["silent_e"]),
  makeWord(3, "vine", "A long climbing plant", "nature", "vine", "🌿", ["silent_e"]),
  makeWord(3, "voice", "The sound you make when you speak", "body", "voice", "🗣️", ["silent_e"]),
  makeWord(3, "vote", "Choose in an election", "school", "vote", "🗳️", ["silent_e"]),
  makeWord(3, "wade", "Walk through shallow water", "action", "wade", "🌊", ["silent_e"]),
  makeWord(3, "wage", "Money earned for working", "school", "wage", "💵", ["silent_e"]),
  makeWord(3, "wake", "Stop sleeping", "action", "wake", "⏰", ["silent_e"]),
  makeWord(3, "waste", "Use more than needed", "action", "waste", "♻️", ["silent_e"]),
  makeWord(3, "wave", "Move your hand as a greeting", "action", "wave", "👋", ["silent_e"]),
  makeWord(3, "while", "During the time that", "school", "while", "⏳", ["silent_e"]),
  makeWord(3, "white", "The lightest colour", "colour", "white", "⬜", ["silent_e"]),
  makeWord(3, "whole", "All of something", "description", "whole", "🔵", ["silent_e"]),
  makeWord(3, "wide", "Large from side to side", "description", "wide", "↔️", ["silent_e"]),
  makeWord(3, "wise", "Having good knowledge and judgement", "description", "wise", "🦉", ["silent_e"]),
  makeWord(3, "woke", "Became aware", "action", "woke", "⏰", ["silent_e"]),
  makeWord(3, "wrote", "Made words with a pen in the past", "action", "wrote", "✍️", ["silent_e"]),
  makeWord(3, "zone", "An area with a specific purpose", "school", "zone", "📍", ["silent_e"]),
  // More compound words
  makeWord(3, "backpack", "A bag you wear on your back", "school", "back-pack", "🎒", ["compound"]),
  makeWord(3, "bookshelf", "Furniture to store books", "home", "book-shelf", "📚", ["compound"]),
  makeWord(3, "butterfly", "A beautiful flying insect", "animal", "but-ter-fly", "🦋", ["compound"]),
  makeWord(3, "candlelight", "Light from a candle", "home", "can-dle-light", "🕯️", ["compound"]),
  makeWord(3, "caretaker", "Someone who looks after a building", "people", "care-tak-er", "🧹", ["compound"]),
  makeWord(3, "cornfield", "A field of growing corn", "nature", "corn-field", "🌽", ["compound"]),
  makeWord(3, "crossword", "A word puzzle in a grid", "school", "cross-word", "📰", ["compound"]),
  makeWord(3, "daydream", "A pleasant thought while awake", "thinking", "day-dream", "💭", ["compound"]),
  makeWord(3, "driftwood", "Wood washed up on a beach", "nature", "drift-wood", "🪵", ["compound"]),
  makeWord(3, "eardrum", "The part inside your ear that vibrates", "body", "ear-drum", "👂", ["compound"]),
  makeWord(3, "earthworm", "A worm that lives in soil", "animal", "earth-worm", "🪱", ["compound"]),
  makeWord(3, "eyelid", "The skin that closes over your eye", "body", "eye-lid", "👁️", ["compound"]),
  makeWord(3, "farmyard", "The area around a farm", "place", "farm-yard", "🚜", ["compound"]),
  makeWord(3, "firework", "An explosive that makes colourful lights", "celebration", "fire-work", "🎆", ["compound"]),
  makeWord(3, "flashlight", "A handheld electric torch", "object", "flash-light", "🔦", ["compound"]),
  makeWord(3, "flowerpot", "A container for growing plants", "home", "flow-er-pot", "🪴", ["compound"]),
  makeWord(3, "foghorn", "A loud horn used in fog", "object", "fog-horn", "📣", ["compound"]),
  makeWord(3, "footprint", "A mark left by a foot", "nature", "foot-print", "👣", ["compound"]),
  makeWord(3, "grassland", "A wide open area of grass", "nature", "grass-land", "🌾", ["compound"]),
  makeWord(3, "hairbrush", "A brush to tidy your hair", "home", "hair-brush", "💇", ["compound"]),
  makeWord(3, "handshake", "Greet someone by holding hands", "action", "hand-shake", "🤝", ["compound"]),
  makeWord(3, "headband", "A band worn around the head", "clothes", "head-band", "🎀", ["compound"]),
  makeWord(3, "heartbeat", "The pumping of your heart", "body", "heart-beat", "❤️", ["compound"]),
  makeWord(3, "hillside", "The sloping side of a hill", "nature", "hill-side", "⛰️", ["compound"]),
  makeWord(3, "homework", "School work done at home", "school", "home-work", "📖", ["compound"]),
  makeWord(3, "honeybee", "A bee that makes honey", "animal", "hon-ey-bee", "🐝", ["compound"]),
  makeWord(3, "hourglass", "A timer using falling sand", "object", "hour-glass", "⏳", ["compound"]),
  makeWord(3, "iceberg", "A huge floating block of ice", "nature", "ice-berg", "🧊", ["compound"]),
  makeWord(3, "jellyfish", "A soft sea creature", "animal", "jel-ly-fish", "🪼", ["compound"]),
  makeWord(3, "keyboard", "Keys you type on", "technology", "key-board", "⌨️", ["compound"]),
  makeWord(3, "kneecap", "The bone at the front of your knee", "body", "knee-cap", "🦵", ["compound"]),
  makeWord(3, "landscape", "The scenery of an area", "nature", "land-scape", "🏞️", ["compound"]),
  makeWord(3, "lighthouse", "A tower with a flashing light to guide ships", "place", "light-house", "🗼", ["compound"], undefined, "image", "/spelling-icons/lighthouse.svg"),
  makeWord(3, "mailbox", "A box for letters and parcels", "home", "mail-box", "📮", ["compound"]),
  makeWord(3, "midnight", "Twelve o'clock at night", "time", "mid-night", "🌙", ["compound"]),
  makeWord(3, "moonlight", "Light from the moon", "nature", "moon-light", "🌕", ["compound"]),
  makeWord(3, "mountaintop", "The highest point of a mountain", "nature", "moun-tain-top", "⛰️", ["compound"]),
  makeWord(3, "necktie", "A strip of fabric worn around the neck", "clothes", "neck-tie", "👔", ["compound"]),
  makeWord(3, "nightfall", "When darkness begins", "time", "night-fall", "🌆", ["compound"]),
  makeWord(3, "outshine", "Be brighter than others", "action", "out-shine", "✨", ["compound"]),
  makeWord(3, "overalls", "Trousers with a bib and straps", "clothes", "o-ver-alls", "👖", ["compound"]),
  makeWord(3, "overnight", "Through the whole night", "time", "o-ver-night", "🌙", ["compound"]),
  makeWord(3, "overture", "The opening music of a show", "music", "o-ver-ture", "🎼", ["compound"]),
  makeWord(3, "pancake", "A flat round food cooked in a pan", "food", "pan-cake", "🥞", ["compound"]),
  makeWord(3, "password", "A secret word to get access", "technology", "pass-word", "🔐", ["compound"]),
  makeWord(3, "patchwork", "Pieces of fabric sewn together", "art", "patch-work", "🧵", ["compound"]),
  makeWord(3, "pinecone", "A seed case from a pine tree", "nature", "pine-cone", "🌲", ["compound"]),
  makeWord(3, "pocketbook", "A small book or diary", "school", "pock-et-book", "📕", ["compound"]),
  makeWord(3, "quicksand", "Wet sand that you can sink into", "nature", "quick-sand", "🏜️", ["compound"]),
  makeWord(3, "raindrop", "A single drop of rain", "weather", "rain-drop", "🌧️", ["compound"]),
  makeWord(3, "riverbank", "The edge of a river", "nature", "riv-er-bank", "🏞️", ["compound"]),
  makeWord(3, "roadside", "The edge of a road", "place", "road-side", "🛣️", ["compound"]),
  makeWord(3, "rooftop", "The top of a building", "place", "roof-top", "🏠", ["compound"]),
  makeWord(3, "sandcastle", "A castle built from sand", "play", "sand-cas-tle", "🏰", ["compound"]),
  makeWord(3, "scarecrow", "A figure in a field to scare birds", "farm", "scare-crow", "🌾", ["compound"]),
  makeWord(3, "schoolbag", "A bag used to carry school things", "school", "school-bag", "🎒", ["compound"]),
  makeWord(3, "seashell", "A shell from the sea", "nature", "sea-shell", "🐚", ["compound"]),
  makeWord(3, "seashore", "Where the sea meets the land", "nature", "sea-shore", "🏖️", ["compound"]),
  makeWord(3, "seaweed", "A plant that grows in the sea", "nature", "sea-weed", "🌿", ["compound"]),
  makeWord(3, "shellfish", "Sea creatures with shells", "animal", "shell-fish", "🦀", ["compound"]),
  makeWord(3, "shipwreck", "A wrecked or sunken ship", "history", "ship-wreck", "⚓", ["compound"]),
  makeWord(3, "shoestring", "A shoelace", "clothes", "shoe-string", "👟", ["compound"]),
  makeWord(3, "sidewalk", "A pavement for walking", "place", "side-walk", "🚶", ["compound"]),
  makeWord(3, "signpost", "A sign showing directions", "place", "sign-post", "🪧", ["compound"]),
  makeWord(3, "sketchbook", "A book for drawing", "art", "sketch-book", "✏️", ["compound"]),
  makeWord(3, "skyline", "The outline of buildings against the sky", "place", "sky-line", "🌆", ["compound"]),
  makeWord(3, "sleepover", "When you stay the night at a friend's house", "play", "sleep-o-ver", "🛏️", ["compound"]),
  makeWord(3, "slideshow", "A set of pictures shown one after another", "school", "slide-show", "🖥️", ["compound"]),
  makeWord(3, "snowball", "A ball made of snow", "play", "snow-ball", "❄️", ["compound"]),
  makeWord(3, "snowboard", "A board for riding on snow", "sport", "snow-board", "🏂", ["compound"]),
  makeWord(3, "snowman", "A figure made from snow", "play", "snow-man", "☃️", ["compound"]),
  makeWord(3, "somewhere", "In some place", "position", "some-where", "📍", ["compound"]),
  makeWord(3, "spacecraft", "A vehicle for travelling in space", "science", "space-craft", "🚀", ["compound"]),
  makeWord(3, "speakeasy", "A secret place", "history", "speak-eas-y", "🤫", ["compound"]),
  makeWord(3, "springtime", "The season of spring", "time", "spring-time", "🌸", ["compound"]),
  makeWord(3, "staircase", "Steps going up or down", "home", "stair-case", "🪜", ["compound"]),
  makeWord(3, "storybook", "A book of stories", "school", "sto-ry-book", "📚", ["compound"]),
  makeWord(3, "streetlight", "A lamp on a street", "place", "street-light", "💡", ["compound"]),
  makeWord(3, "suitcase", "A large bag for travelling", "travel", "suit-case", "🧳", ["compound"]),
  makeWord(3, "sunburn", "Sore skin from too much sun", "body", "sun-burn", "☀️", ["compound"]),
  makeWord(3, "sunflower", "A tall flower that faces the sun", "nature", "sun-flow-er", "🌻", ["compound"]),
  makeWord(3, "sunlight", "Light from the sun", "nature", "sun-light", "☀️", ["compound"]),
  makeWord(3, "sunrise", "When the sun comes up in the morning", "time", "sun-rise", "🌅", ["compound"]),
  makeWord(3, "sunset", "When the sun goes down in the evening", "time", "sun-set", "🌇", ["compound"]),
  makeWord(3, "supermarket", "A large shop with many different foods", "place", "su-per-mar-ket", "🛒", ["compound"]),
  makeWord(3, "tablecloth", "A cloth laid over a table", "home", "ta-ble-cloth", "🍽️", ["compound"]),
  makeWord(3, "teamwork", "Working together as a team", "school", "team-work", "🤝", ["compound"]),
  makeWord(3, "textbook", "A book used for studying", "school", "text-book", "📘", ["compound"]),
  makeWord(3, "thunderstorm", "A storm with thunder and lightning", "weather", "thun-der-storm", "⛈️", ["compound"]),
  makeWord(3, "timetable", "A list showing when things happen", "school", "time-ta-ble", "📅", ["compound"]),
  makeWord(3, "toothbrush", "A brush to clean your teeth", "home", "tooth-brush", "🪥", ["compound"]),
  makeWord(3, "toothpaste", "Paste used to clean your teeth", "home", "tooth-paste", "🦷", ["compound"]),
  makeWord(3, "townhall", "A building where local government meets", "place", "town-hall", "🏛️", ["compound"]),
  makeWord(3, "treehouse", "A small house built in a tree", "play", "tree-house", "🌳", ["compound"]),
  makeWord(3, "treetrunk", "The main stem of a tree", "nature", "tree-trunk", "🪵", ["compound"]),
  makeWord(3, "twilight", "The soft light just after sunset", "time", "twi-light", "🌆", ["compound"]),
  makeWord(3, "underline", "A line drawn under a word", "school", "un-der-line", "📝", ["compound"]),
  makeWord(3, "upstairs", "The upper floor of a building", "home", "up-stairs", "🪜", ["compound"]),
  makeWord(3, "viewpoint", "A place with a great view", "place", "view-point", "👁️", ["compound"]),
  makeWord(3, "volleyball", "A sport played with a large ball", "sport", "vol-ley-ball", "🏐", ["compound"]),
  makeWord(3, "walkway", "A path for walking", "place", "walk-way", "🚶", ["compound"]),
  makeWord(3, "wardrobe", "A large cupboard for clothes", "home", "ward-robe", "🚪", ["compound"]),
  makeWord(3, "watchdog", "A dog kept to guard a place", "animal", "watch-dog", "🐕", ["compound"]),
  makeWord(3, "watercolour", "A type of paint mixed with water", "art", "wa-ter-col-our", "🎨", ["compound"]),
  makeWord(3, "watermelon", "A large green fruit with red flesh", "food", "wa-ter-mel-on", "🍉", ["compound"]),
  makeWord(3, "weekend", "Saturday and Sunday", "time", "week-end", "🎉", ["compound"]),
  makeWord(3, "whirlpool", "Water spinning in a circle", "nature", "whirl-pool", "🌀", ["compound"]),
  makeWord(3, "wildflower", "A flower that grows in the wild", "nature", "wild-flow-er", "🌼", ["compound"]),
  makeWord(3, "windmill", "A machine powered by wind", "object", "wind-mill", "🏗️", ["compound"]),
  makeWord(3, "woodpecker", "A bird that pecks at trees", "animal", "wood-peck-er", "🐦", ["compound"]),
  makeWord(3, "workout", "Exercise to keep fit", "sport", "work-out", "💪", ["compound"]),
  makeWord(3, "worldwide", "All over the world", "description", "world-wide", "🌍", ["compound"]),
  makeWord(3, "wristwatch", "A watch worn on the wrist", "object", "wrist-watch", "⌚", ["compound"]),
  makeWord(3, "yourself", "You alone", "description", "your-self", "🪞", ["compound"]),
];

const L4: SpellingWordBankEntry[] = [
  makeWord(4, "ball", "You throw and catch it", "play", "ball", "⚽", ["double_letter"]),
  makeWord(4, "bell", "It rings", "object", "bell", "🔔", ["double_letter"]),
  makeWord(4, "hill", "A small mountain", "nature", "hill", "⛰️", ["double_letter"]),
  makeWord(4, "duck", "A bird that swims", "animal", "duck", "🦆", ["ck_end"]),
  makeWord(4, "sock", "You wear it on your foot", "clothes", "sock", "🧦", ["ck_end"]),
  makeWord(4, "kick", "Hit with your foot", "action", "kick", "🦶", ["ck_end"]),
  makeWord(4, "light", "Bright and helps you see", "nature", "light", "💡", ["igh", "ight"]),
  makeWord(4, "night", "When it is dark", "time", "night", "🌙", ["igh", "ight"]),
  makeWord(4, "right", "Opposite of left", "position", "right", "➡️", ["igh", "ight"]),
  makeWord(4, "fight", "A battle", "action", "fight", "🥊", ["igh", "ight"]),
  makeWord(4, "bright", "Full of light", "description", "bright", "🌟", ["igh", "ight"]),
  makeWord(4, "sight", "The ability to see", "body", "sight", "👁️", ["igh", "ight"]),
  makeWord(4, "catch", "Grab something moving", "action", "catch", "🤲", ["ch"]),
  makeWord(4, "match", "Two things that go together", "object", "match", "🧩", ["ch"]),
  makeWord(4, "watch", "You wear it to tell time", "object", "watch", "⌚", ["ch"]),
  makeWord(4, "happy", "Feeling good", "feeling", "hap-py", "😀", ["double_letter"]),
  makeWord(4, "kitten", "A baby cat", "animal", "kit-ten", "🐱", ["double_letter"]),
  makeWord(4, "puppy", "A baby dog", "animal", "pup-py", "🐶", ["double_letter"]),
  makeWord(4, "middle", "The centre", "position", "mid-dle", "🎯", ["double_letter"]),
  makeWord(4, "apple", "A red or green fruit", "food", "ap-ple", "🍎", ["double_letter"]),
  makeWord(4, "puzzle", "A game with pieces", "play", "puz-zle", "🧩", ["double_letter", "silent_e"]),
  makeWord(4, "people", "More than one person", "people", "peo-ple", "👥", ["silent_e"]),
  makeWord(4, "castle", "A big old building", "place", "cas-tle", "🏰", ["silent_e"]),
  makeWord(4, "ticket", "Paper or code for entry", "object", "tick-et", "🎟️", ["ck_end"]),
  makeWord(4, "thunder", "A loud sound during a storm", "weather", "thun-der", "⛈️", ["th"]),
  // Multi-syllable words — 3+ syllables, longer and more challenging
  makeWord(4, "together", "With each other", "people", "to-geth-er", "🤝", ["multi"]),
  makeWord(4, "important", "Very meaningful or needed", "school", "im-por-tant", "❗", ["multi"]),
  makeWord(4, "remember", "To keep in your mind", "thinking", "re-mem-ber", "🧠", ["multi"]),
  makeWord(4, "beautiful", "Very pretty or lovely", "description", "beau-ti-ful", "🌸", ["multi"]),
  makeWord(4, "exciting", "Causing great happiness", "feeling", "ex-cit-ing", "🎉", ["multi"]),
  makeWord(4, "wonderful", "Amazing and great", "description", "won-der-ful", "✨", ["multi"]),
  makeWord(4, "adventure", "An exciting journey", "action", "ad-ven-ture", "🗺️", ["multi", "silent_e"]),
  makeWord(4, "different", "Not the same", "description", "dif-ferent", "🔄", ["multi", "double_letter"]),
  makeWord(4, "afternoon", "The time after midday", "time", "af-ter-noon", "🌤️", ["multi", "double_letter"]),
  makeWord(4, "waterfall", "Water falling down rocks", "nature", "wa-ter-fall", "🌊", ["compound", "double_letter"]),
  makeWord(4, "tomorrow", "The day after today", "time", "to-mor-row", "📅", ["multi", "double_letter"]),
  makeWord(4, "everyone", "Every single person", "people", "ev-ery-one", "👥", ["multi"]),
  // More Level 4 — double letters, vowel patterns, tricky spellings
  makeWord(4, "accept", "Agree to receive something", "school", "ac-cept", "✅", ["double_letter"]),
  makeWord(4, "accident", "Something unexpected that happens", "school", "ac-ci-dent", "⚠️", ["double_letter"]),
  makeWord(4, "accompany", "Go somewhere with someone", "action", "ac-com-pa-ny", "🤝", ["double_letter"]),
  makeWord(4, "accurate", "Exactly right", "description", "ac-cu-rate", "🎯", ["double_letter"]),
  makeWord(4, "address", "The place where someone lives", "school", "ad-dress", "🏠", ["double_letter"]),
  makeWord(4, "afford", "Have enough money to buy", "school", "af-ford", "💰", ["double_letter"]),
  makeWord(4, "afford", "Have enough money to buy", "school", "af-ford", "💰", ["double_letter"]),
  makeWord(4, "allow", "Let something happen", "action", "al-low", "✅", ["double_letter"]),
  makeWord(4, "announce", "Tell people something", "action", "an-nounce", "📢", ["double_letter"]),
  makeWord(4, "appear", "Come into view", "action", "ap-pear", "✨", ["double_letter"]),
  makeWord(4, "apple", "A red or green fruit", "food", "ap-ple", "🍎", ["double_letter"]),
  makeWord(4, "approach", "Come closer to something", "action", "ap-proach", "➡️", ["double_letter"]),
  makeWord(4, "arrow", "A pointed weapon shot from a bow", "object", "ar-row", "🏹", ["double_letter"]),
  makeWord(4, "attend", "Be present at something", "action", "at-tend", "✅", ["double_letter"]),
  makeWord(4, "attic", "A room at the top of a house", "home", "at-tic", "🏠", ["double_letter"]),
  makeWord(4, "attract", "Draw something towards you", "action", "at-tract", "🧲", ["double_letter"]),
  makeWord(4, "balloon", "A rubber bag filled with air", "play", "bal-loon", "🎈", ["double_letter"]),
  makeWord(4, "battery", "Stores electrical energy", "technology", "bat-ter-y", "🔋", ["double_letter"]),
  makeWord(4, "bottle", "A container for liquids", "home", "bot-tle", "🍶", ["double_letter"]),
  makeWord(4, "bottom", "The lowest part", "position", "bot-tom", "⬇️", ["double_letter"]),
  makeWord(4, "button", "A small fastener on clothes", "clothes", "but-ton", "🪡", ["double_letter"]),
  makeWord(4, "carry", "Hold and take somewhere", "action", "car-ry", "🧳", ["double_letter"]),
  makeWord(4, "catfish", "A type of freshwater fish", "animal", "cat-fish", "🐟", ["double_letter"]),
  makeWord(4, "coffee", "A hot drink made from beans", "food", "cof-fee", "☕", ["double_letter"]),
  makeWord(4, "collar", "The part of a shirt around the neck", "clothes", "col-lar", "👔", ["double_letter"]),
  makeWord(4, "collect", "Gather things together", "action", "col-lect", "🧺", ["double_letter"]),
  makeWord(4, "connect", "Join things together", "action", "con-nect", "🔗", ["double_letter"]),
  makeWord(4, "correct", "Right or without mistakes", "school", "cor-rect", "✅", ["double_letter"]),
  makeWord(4, "cotton", "A soft natural fabric", "clothes", "cot-ton", "🧵", ["double_letter"]),
  makeWord(4, "current", "Flow of water or electricity", "science", "cur-rent", "🌊", ["double_letter"]),
  makeWord(4, "dinner", "The main meal of the day", "food", "din-ner", "🍽️", ["double_letter"]),
  makeWord(4, "effort", "Try hard at something", "action", "ef-fort", "💪", ["double_letter"]),
  makeWord(4, "effect", "A result of something", "school", "ef-fect", "💥", ["double_letter"]),
  makeWord(4, "eleven", "The number after ten", "number", "e-lev-en", "1️⃣1️⃣", ["double_letter"]),
  makeWord(4, "error", "A mistake", "school", "er-ror", "❌", ["double_letter"]),
  makeWord(4, "excellent", "Very very good", "description", "ex-cel-lent", "⭐", ["double_letter"]),
  makeWord(4, "express", "Put thoughts into words", "action", "ex-press", "🗣️", ["double_letter"]),
  makeWord(4, "fallen", "Dropped down", "action", "fall-en", "🍂", ["double_letter"]),
  makeWord(4, "fellow", "A man or boy", "people", "fel-low", "🧑", ["double_letter"]),
  makeWord(4, "filling", "What is put inside something", "food", "fill-ing", "🥪", ["double_letter"]),
  makeWord(4, "follow", "Go after someone", "action", "fol-low", "👣", ["double_letter"]),
  makeWord(4, "funny", "Making you laugh", "description", "fun-ny", "😂", ["double_letter"]),
  makeWord(4, "gotten", "Past tense of get", "school", "got-ten", "📖", ["double_letter"]),
  makeWord(4, "grammar", "The rules of a language", "school", "gram-mar", "📝", ["double_letter"]),
  makeWord(4, "happen", "Take place", "action", "hap-pen", "❓", ["double_letter"]),
  makeWord(4, "hidden", "Out of sight", "description", "hid-den", "🙈", ["double_letter"]),
  makeWord(4, "hollow", "Empty inside", "description", "hol-low", "🕳️", ["double_letter"]),
  makeWord(4, "horror", "Extreme fear", "feeling", "hor-ror", "😱", ["double_letter"]),
  makeWord(4, "hurry", "Move quickly", "action", "hur-ry", "🏃", ["double_letter"]),
  makeWord(4, "illness", "Being sick", "health", "ill-ness", "🤒", ["double_letter"]),
  makeWord(4, "innocent", "Not guilty", "school", "in-no-cent", "😇", ["double_letter"]),
  makeWord(4, "kettle", "A pot for boiling water", "home", "ket-tle", "🫖", ["double_letter"]),
  makeWord(4, "knotted", "Tied in a knot", "description", "knot-ted", "🪢", ["double_letter"]),
  makeWord(4, "ladder", "Rungs you climb up", "object", "lad-der", "🪜", ["double_letter"]),
  makeWord(4, "letter", "A written message or an alphabet symbol", "school", "let-ter", "✉️", ["double_letter"]),
  makeWord(4, "little", "Small in size", "description", "lit-tle", "🤏", ["double_letter"]),
  makeWord(4, "litter", "Rubbish left on the ground", "nature", "lit-ter", "🗑️", ["double_letter"]),
  makeWord(4, "llama", "An animal similar to a camel", "animal", "lla-ma", "🦙", ["double_letter"]),
  makeWord(4, "mammoth", "An extinct elephant-like animal", "history", "mam-moth", "🦣", ["double_letter"]),
  makeWord(4, "manner", "The way you do something", "school", "man-ner", "🤝", ["double_letter"]),
  makeWord(4, "matter", "What something is made of", "science", "mat-ter", "⚛️", ["double_letter"]),
  makeWord(4, "mirror", "A reflective glass surface", "home", "mir-ror", "🪞", ["double_letter"]),
  makeWord(4, "mitten", "A warm covering for the hand", "clothes", "mit-ten", "🧤", ["double_letter"]),
  makeWord(4, "muffin", "A small round cake", "food", "muf-fin", "🧁", ["double_letter"]),
  makeWord(4, "mussel", "A type of shellfish", "food", "mus-sel", "🦪", ["double_letter"]),
  makeWord(4, "noodle", "Long thin pasta", "food", "noo-dle", "🍜", ["double_letter"]),
  makeWord(4, "offer", "Propose something to someone", "action", "of-fer", "🤝", ["double_letter"]),
  makeWord(4, "office", "A room where people work", "place", "of-fice", "🏢", ["double_letter"]),
  makeWord(4, "opposite", "Completely different or facing", "position", "op-po-site", "↔️", ["double_letter"]),
  makeWord(4, "otter", "A small furry aquatic animal", "animal", "ot-ter", "🦦", ["double_letter"]),
  makeWord(4, "pattern", "A repeated design", "art", "pat-tern", "🔁", ["double_letter"]),
  makeWord(4, "pepper", "A spice or a vegetable", "food", "pep-per", "🌶️", ["double_letter"]),
  makeWord(4, "pillow", "A soft cushion for sleeping", "home", "pil-low", "🛌", ["double_letter"]),
  makeWord(4, "planted", "Put into soil to grow", "nature", "plant-ed", "🌱", ["double_letter"]),
  makeWord(4, "possess", "Own or have something", "action", "pos-sess", "🏠", ["double_letter"]),
  makeWord(4, "pretty", "Pleasing to look at", "description", "pret-ty", "🌸", ["double_letter"]),
  makeWord(4, "puddle", "A small pool of water", "nature", "pud-dle", "💧", ["double_letter"]),
  makeWord(4, "rabbit", "An animal with long ears", "animal", "rab-bit", "🐰", ["double_letter"]),
  makeWord(4, "rattle", "Make a rattling noise", "action", "rat-tle", "🔔", ["double_letter"]),
  makeWord(4, "ribbon", "A thin strip of fabric", "object", "rib-bon", "🎀", ["double_letter"]),
  makeWord(4, "riddle", "A puzzle or tricky question", "school", "rid-dle", "❓", ["double_letter"]),
  makeWord(4, "rubbish", "Waste material", "home", "rub-bish", "🗑️", ["double_letter"]),
  makeWord(4, "rubber", "A stretchy material", "object", "rub-ber", "✏️", ["double_letter"]),
  makeWord(4, "saddle", "Seat for riding a horse", "sport", "sad-dle", "🐴", ["double_letter"]),
  makeWord(4, "scatter", "Throw about in different directions", "action", "scat-ter", "💥", ["double_letter"]),
  makeWord(4, "scissors", "A tool for cutting", "object", "scis-sors", "✂️", ["double_letter"]),
  makeWord(4, "seller", "Someone who sells things", "people", "sell-er", "🛍️", ["double_letter"]),
  makeWord(4, "settle", "Make yourself comfortable", "action", "set-tle", "🛋️", ["double_letter"]),
  makeWord(4, "shallow", "Not deep", "description", "shal-low", "🏖️", ["double_letter"]),
  makeWord(4, "silly", "Funny in a childish way", "description", "sil-ly", "🤡", ["double_letter"]),
  makeWord(4, "simmer", "Cook gently in hot liquid", "action", "sim-mer", "🍲", ["double_letter"]),
  makeWord(4, "sizzle", "Make a hissing sound when cooking", "action", "siz-zle", "🍳", ["double_letter"]),
  makeWord(4, "skill", "Ability to do something well", "school", "skill", "🎯", ["double_letter"]),
  makeWord(4, "skull", "The bony head structure", "body", "skull", "💀", ["double_letter"]),
  makeWord(4, "small", "Little in size", "description", "small", "🤏", ["double_letter"]),
  makeWord(4, "smell", "Sense with your nose", "body", "smell", "👃", ["double_letter"]),
  makeWord(4, "sniff", "Breathe in through your nose", "action", "sniff", "👃", ["double_letter"]),
  makeWord(4, "soccer", "A sport played with a round ball", "sport", "soc-cer", "⚽", ["double_letter"]),
  makeWord(4, "sorry", "Feeling regret", "feeling", "sor-ry", "😔", ["double_letter"]),
  makeWord(4, "spell", "Say or write the letters of a word", "school", "spell", "✏️", ["double_letter"]),
  makeWord(4, "spill", "Let liquid fall by accident", "action", "spill", "💦", ["double_letter"]),
  makeWord(4, "staff", "People who work somewhere", "people", "staff", "👨‍💼", ["double_letter"]),
  makeWord(4, "stiff", "Hard and not bendy", "description", "stiff", "🧊", ["double_letter"]),
  makeWord(4, "still", "Not moving", "description", "still", "🧘", ["double_letter"]),
  makeWord(4, "stuff", "Objects or material", "object", "stuff", "📦", ["double_letter"]),
  makeWord(4, "summer", "The hottest season", "time", "sum-mer", "☀️", ["double_letter"]),
  makeWord(4, "support", "Help and encourage", "action", "sup-port", "🤝", ["double_letter"]),
  makeWord(4, "suppose", "Think that something is likely", "thinking", "sup-pose", "🤔", ["double_letter"]),
  makeWord(4, "supper", "An evening meal", "food", "sup-per", "🍽️", ["double_letter"]),
  makeWord(4, "swagger", "Walk with great confidence", "action", "swag-ger", "😎", ["double_letter"]),
  makeWord(4, "swimmer", "Someone who swims", "sport", "swim-mer", "🏊", ["double_letter"]),
  makeWord(4, "terror", "Extreme fear", "feeling", "ter-ror", "😱", ["double_letter"]),
  makeWord(4, "toffee", "A sticky sweet", "food", "tof-fee", "🍬", ["double_letter"]),
  makeWord(4, "tunnel", "An underground passage", "place", "tun-nel", "🚇", ["double_letter"]),
  makeWord(4, "until", "Up to the point of", "school", "un-til", "⏳", ["double_letter"]),
  makeWord(4, "upper", "Higher in position", "position", "up-per", "⬆️", ["double_letter"]),
  makeWord(4, "village", "A small community", "place", "vil-lage", "🏘️", ["double_letter"]),
  makeWord(4, "villain", "An evil character in a story", "school", "vil-lain", "😈", ["double_letter"]),
  makeWord(4, "waffle", "A crispy gridded food", "food", "waf-fle", "🧇", ["double_letter"]),
  makeWord(4, "wallet", "A small case for cards and cash", "object", "wal-let", "💳", ["double_letter"], undefined, "image", "/spelling-icons/wallet.svg"),
  makeWord(4, "whipped", "Beat quickly to make fluffy", "food", "whipped", "🍦", ["double_letter"]),
  makeWord(4, "winner", "Someone who wins", "sport", "win-ner", "🏆", ["double_letter"]),
  makeWord(4, "written", "Set down in writing", "school", "writ-ten", "📝", ["double_letter"]),
  makeWord(4, "yellow", "A bright sunny colour", "colour", "yel-low", "💛", ["double_letter"]),
  makeWord(4, "yelling", "Shouting loudly", "action", "yell-ing", "📣", ["double_letter"]),
  makeWord(4, "yoghurt", "A creamy dairy food", "food", "yog-hurt", "🥛", ["double_letter"]),
];

const L5: SpellingWordBankEntry[] = [
  makeWord(5, "phone", "You call people with it", "technology", "phone", "📱", ["ph", "silent_e"], "She called her friend on the phone."),
  makeWord(5, "graph", "Shows data in a picture", "maths", "graph", "📈", ["ph"], "The scientist drew a graph of the results."),
  makeWord(5, "photo", "A picture taken by a camera", "technology", "pho-to", "📷", ["ph"], "We took a family photo at the park."),
  makeWord(5, "elephant", "A very large animal with a trunk", "animal", "el-e-phant", "🐘", ["ph"], "The elephant splashed water with its trunk."),
  makeWord(5, "dolphin", "A clever sea animal", "animal", "dol-phin", "🐬", ["ph"], "A dolphin jumped out of the sparkling water."),
  makeWord(5, "action", "Something that is happening", "school", "ac-tion", "🎬", ["tion"], "The superhero sprang into action to help."),
  makeWord(5, "station", "Where trains or buses stop", "place", "sta-tion", "🚉", ["tion"], "The train pulled into the busy station."),
  makeWord(5, "fiction", "A made-up story", "reading", "fic-tion", "📖", ["tion"], "Harry Potter is a famous work of fiction."),
  makeWord(5, "question", "Something you ask to find out", "school", "ques-tion", "❓", ["tion"], "The teacher asked us a tricky question."),
  makeWord(5, "solution", "An answer that fixes a problem", "maths", "so-lu-tion", "✅", ["tion"], "We worked together to find a solution."),
  makeWord(5, "through", "Going in one side and out the other", "position", "through", "➡️", ["ough"], "The ball flew through the hoop perfectly."),
  makeWord(5, "thought", "An idea in your mind", "thinking", "thought", "💭", ["ough"], "She had a wonderful thought during class."),
  makeWord(5, "enough", "As much as is needed", "description", "e-nough", "✅", ["ough"], "There was enough cake for everyone at the party."),
  makeWord(5, "rough", "Not smooth to touch", "description", "rough", "🪨", ["ough"], "The rough path was hard to walk on."),
  makeWord(5, "cough", "A sudden sound from the throat", "body", "cough", "🤧", ["ough"], "He had a bad cough and stayed home from school."),
  makeWord(5, "write", "Make letters and words on paper", "school", "write", "✍️", ["wr", "silent_e"], "She loves to write stories about dragons."),
  makeWord(5, "wrong", "Not correct or right", "school", "wrong", "❌", ["wr"], "I got the answer wrong and tried again."),
  makeWord(5, "wrist", "The joint between your hand and arm", "body", "wrist", "🤚", ["wr"], "She wore a sparkly bracelet on her wrist."),
  makeWord(5, "knife", "A sharp tool used carefully for cutting", "object", "knife", "🔪", ["kn", "silent_e"], "The chef used a knife to chop the vegetables."),
  makeWord(5, "knee", "The middle joint of your leg", "body", "knee", "🦵", ["kn", "double_letter"], "He bent his knee to tie his shoe."),
  makeWord(5, "knock", "Tap firmly on a door", "action", "knock", "🚪", ["kn", "ck_end"], "Please knock on the door before coming in."),
  makeWord(5, "know", "To understand or be sure of something", "thinking", "know", "🧠", ["kn"], "Do you know the answer to the puzzle?"),
  makeWord(5, "imagination", "The ability to create ideas in your mind", "thinking", "i-mag-i-na-tion", "🌈", ["tion"], "She used her imagination to paint a wonderful picture."),
  makeWord(5, "information", "Facts that help you understand something", "school", "in-for-ma-tion", "ℹ️", ["tion"], "The book was full of useful information."),
  makeWord(5, "celebration", "A happy event to mark something special", "time", "cel-e-bra-tion", "🎉", ["tion"], "The whole class joined in the celebration."),
  // Advanced complex spellings
  makeWord(5, "necessary", "Something that must be done or had", "school", "nec-es-sa-ry", "📌", ["multi"], "It is necessary to wear a helmet when cycling."),
  makeWord(5, "environment", "The natural world around us", "science", "en-vi-ron-ment", "🌍", ["multi"], "We must look after our environment."),
  makeWord(5, "temperature", "How hot or cold something is", "science", "tem-per-a-ture", "🌡️", ["multi"], "The temperature dropped overnight."),
  makeWord(5, "Wednesday", "The middle day of the school week", "time", "Wednes-day", "📅", ["silent_d"], "On Wednesday we have art and music."),
  makeWord(5, "February", "The second month of the year", "time", "Feb-ru-a-ry", "📆", ["multi"], "February is the shortest month."),
  // More Level 5 — complex patterns, silent letters, tricky high-frequency words
  makeWord(5, "absence", "Not being somewhere", "school", "ab-sence", "🚫", ["silent_c"], "Her absence from class was noticed."),
  makeWord(5, "accommodate", "Have enough room for", "school", "ac-com-mo-date", "🏨", ["double_letter"], "The hotel can accommodate fifty guests."),
  makeWord(5, "achieve", "Succeed at something", "school", "a-chieve", "🏆", ["ie"], "She worked hard to achieve her goal."),
  makeWord(5, "acknowledge", "Admit or recognise something", "school", "ac-knowl-edge", "✅", ["kn"], "Please acknowledge that you received the letter."),
  makeWord(5, "acquisition", "Something gained or obtained", "school", "ac-qui-si-tion", "📦", ["tion"], "The museum made a new acquisition."),
  makeWord(5, "adequate", "Enough to satisfy a need", "description", "ad-e-quate", "✅", ["multi"], "The food was adequate for the journey."),
  makeWord(5, "adjacent", "Next to or beside", "position", "ad-ja-cent", "↔️", ["multi"], "Our classroom is adjacent to the library."),
  makeWord(5, "admirable", "Deserving respect", "description", "ad-mi-ra-ble", "🌟", ["multi"], "Her courage was truly admirable."),
  makeWord(5, "advertisement", "A message to promote something", "school", "ad-ver-tise-ment", "📢", ["multi"], "The advertisement appeared on television."),
  makeWord(5, "aggressive", "Very forceful or hostile", "description", "ag-gres-sive", "😡", ["double_letter"], "The aggressive dog frightened the children."),
  makeWord(5, "ambulance", "A vehicle that takes sick people to hospital", "health", "am-bu-lance", "🚑", ["multi"], "The ambulance arrived in minutes."),
  makeWord(5, "ancient", "Very very old", "history", "an-cient", "🏛️", ["multi"], "The ancient ruins were thousands of years old."),
  makeWord(5, "apparent", "Clear and obvious", "description", "ap-par-ent", "🔍", ["double_letter"], "It was apparent that she had practised hard."),
  makeWord(5, "appreciate", "Be grateful for something", "feeling", "ap-pre-ci-ate", "🙏", ["multi"], "I appreciate all the help you gave me."),
  makeWord(5, "appropriate", "Suitable for the situation", "description", "ap-pro-pri-ate", "✅", ["double_letter"], "Please wear appropriate clothing."),
  makeWord(5, "approximately", "About or nearly", "school", "ap-prox-i-mate-ly", "≈", ["multi"], "It takes approximately twenty minutes."),
  makeWord(5, "argument", "A disagreement using words", "school", "ar-gu-ment", "💬", ["multi"], "They had an argument about the rules."),
  makeWord(5, "arrangement", "How things are organised", "school", "ar-range-ment", "📋", ["double_letter"], "The flower arrangement was beautiful."),
  makeWord(5, "atmosphere", "The air around the Earth", "science", "at-mos-phere", "🌍", ["ph"], "The atmosphere protects us from space."),
  makeWord(5, "audience", "People watching or listening", "school", "au-di-ence", "👥", ["multi"], "The audience clapped loudly at the end."),
  makeWord(5, "available", "Ready to use or get", "description", "a-vail-a-ble", "✅", ["multi"], "The teacher was available after school."),
  makeWord(5, "beginning", "The start of something", "school", "be-gin-ning", "🏁", ["double_letter"], "At the beginning of the story there was a princess."),
  makeWord(5, "behaviour", "The way someone acts", "school", "be-hav-iour", "😊", ["multi"], "Good behaviour is expected in the classroom."),
  makeWord(5, "bicycle", "A vehicle with two wheels and pedals", "transport", "bi-cy-cle", "🚲", ["multi"], "She rides her bicycle to school every day."),
  makeWord(5, "brilliant", "Very bright or very clever", "description", "bril-liant", "🌟", ["double_letter"], "She gave a brilliant performance."),
  makeWord(5, "category", "A group of similar things", "school", "cat-e-go-ry", "📂", ["multi"], "Sort the words into each category."),
  makeWord(5, "character", "A person in a story", "school", "char-ac-ter", "🎭", ["multi"], "The main character was a young wizard."),
  makeWord(5, "circumstances", "The conditions around an event", "school", "cir-cum-stan-ces", "🔍", ["multi"], "Under no circumstances should you leave."),
  makeWord(5, "coincidence", "Two things happening at the same time by chance", "school", "co-in-ci-dence", "😮", ["multi"], "It was a strange coincidence."),
  makeWord(5, "communicate", "Share information with others", "school", "com-mu-ni-cate", "🗣️", ["double_letter"], "We communicate through words and actions."),
  makeWord(5, "community", "A group of people living together", "school", "com-mu-ni-ty", "🏘️", ["double_letter"], "Our community came together to help."),
  makeWord(5, "competition", "A contest to find the winner", "school", "com-pe-ti-tion", "🏆", ["tion"], "She entered the spelling competition."),
  makeWord(5, "concentration", "Focusing your mind on something", "school", "con-cen-tra-tion", "🧘", ["tion"], "The puzzle required great concentration."),
  makeWord(5, "conclusion", "The final part or decision", "school", "con-clu-sion", "🔚", ["tion"], "They reached a conclusion after the meeting."),
  makeWord(5, "consequence", "What happens as a result", "school", "con-se-quence", "💥", ["multi"], "Littering has consequences for the environment."),
  makeWord(5, "continent", "One of the seven large landmasses", "geography", "con-ti-nent", "🌍", ["multi"], "Africa is the second largest continent."),
  makeWord(5, "convenience", "Being easy to use or get", "school", "con-ven-ience", "✅", ["multi"], "The shop is open for your convenience."),
  makeWord(5, "curiosity", "A strong desire to know something", "feeling", "cu-ri-os-i-ty", "🔍", ["multi"], "Her curiosity led her to explore the cave."),
  makeWord(5, "decision", "A choice made after thinking", "school", "de-ci-sion", "🤔", ["tion"], "She made a difficult decision."),
  makeWord(5, "definition", "The meaning of a word", "school", "def-i-ni-tion", "📖", ["tion"], "Look up the definition in the dictionary."),
  makeWord(5, "demonstrate", "Show how something works", "school", "dem-on-strate", "🎭", ["multi"], "The teacher will demonstrate the experiment."),
  makeWord(5, "description", "Words that explain what something is like", "school", "de-scrip-tion", "📝", ["tion"], "Write a description of your favourite place."),
  makeWord(5, "destination", "The place you are travelling to", "travel", "des-ti-na-tion", "📍", ["tion"], "Our destination was Paris."),
  makeWord(5, "determination", "Deciding firmly to do something", "feeling", "de-ter-mi-na-tion", "💪", ["tion"], "Her determination helped her win."),
  makeWord(5, "dictionary", "A book of word meanings", "school", "dic-tion-ar-y", "📖", ["tion"], "Use a dictionary to find the meaning."),
  makeWord(5, "disappear", "Go out of sight", "action", "dis-ap-pear", "👻", ["double_letter"], "The rabbit seemed to disappear by magic."),
  makeWord(5, "disappointed", "Sad because something did not happen", "feeling", "dis-ap-point-ed", "😔", ["double_letter"], "She was disappointed that it rained."),
  makeWord(5, "discussion", "Talking about a topic with others", "school", "dis-cus-sion", "💬", ["double_letter"], "We had a class discussion about climate."),
  makeWord(5, "distinguish", "Tell the difference between things", "school", "dis-tin-guish", "🔍", ["multi"], "Can you distinguish between the two?"),
  makeWord(5, "embarrass", "Make someone feel ashamed or awkward", "feeling", "em-bar-rass", "😳", ["double_letter"], "He did not mean to embarrass her."),
  makeWord(5, "emphasise", "Give special importance to something", "school", "em-pha-sise", "⚠️", ["ph"], "The teacher chose to emphasise key words."),
  makeWord(5, "enormous", "Very very large", "description", "e-nor-mous", "🐘", ["multi"], "The enormous ship filled the harbour."),
  makeWord(5, "enthusiasm", "Great excitement and energy", "feeling", "en-thu-si-asm", "🎉", ["multi"], "She approached the task with enthusiasm."),
  makeWord(5, "especially", "More than usual", "description", "es-pe-cial-ly", "⭐", ["double_letter"], "I especially enjoy reading on weekends."),
  makeWord(5, "evaluation", "Judging how good something is", "school", "e-val-u-a-tion", "📊", ["tion"], "The teacher wrote an evaluation of her work."),
  makeWord(5, "examination", "A formal test of knowledge", "school", "ex-am-i-na-tion", "📝", ["tion"], "She studied hard for the examination."),
  makeWord(5, "exaggerate", "Make something sound bigger than it is", "school", "ex-ag-ger-ate", "📢", ["double_letter"], "Do not exaggerate the size of the fish."),
  makeWord(5, "excellent", "Extremely good", "description", "ex-cel-lent", "🌟", ["double_letter"], "He achieved an excellent result."),
  makeWord(5, "explanation", "Saying why or how something happened", "school", "ex-pla-na-tion", "💡", ["tion"], "She gave a clear explanation."),
  makeWord(5, "extraordinary", "Very unusual or remarkable", "description", "ex-traor-di-na-ry", "🌟", ["multi"], "She had an extraordinary talent for music."),
  makeWord(5, "fascinating", "Extremely interesting", "description", "fas-ci-nat-ing", "🤩", ["multi"], "The documentary was fascinating."),
  makeWord(5, "fluorescent", "Very bright and glowing", "description", "fluo-res-cent", "💡", ["multi"], "The fluorescent light lit up the room."),
  makeWord(5, "frequently", "Very often", "description", "fre-quent-ly", "🔄", ["multi"], "She frequently visits the library."),
  makeWord(5, "generally", "In most cases", "description", "gen-er-al-ly", "📊", ["multi"], "Generally the weather is mild in spring."),
  makeWord(5, "government", "The group that runs a country", "school", "gov-ern-ment", "🏛️", ["multi"], "The government passed a new law."),
  makeWord(5, "guarantee", "A firm promise", "school", "guar-an-tee", "🤝", ["multi"], "There is no guarantee of success."),
  makeWord(5, "hierarchy", "A system ranked from highest to lowest", "school", "hi-er-ar-chy", "📊", ["multi"], "A food chain shows a hierarchy."),
  makeWord(5, "hindrance", "Something that gets in the way", "school", "hin-drance", "🚧", ["multi"], "Noise is a hindrance when studying."),
  makeWord(5, "horizontal", "Going across from left to right", "school", "hor-i-zon-tal", "↔️", ["multi"], "Draw a horizontal line across the page."),
  makeWord(5, "immediately", "Right now, without delay", "description", "im-me-di-ate-ly", "⚡", ["double_letter"], "Please come here immediately."),
  makeWord(5, "independent", "Able to do things without help", "description", "in-de-pen-dent", "🦅", ["multi"], "She was proud to be independent."),
  makeWord(5, "individual", "A single person or thing", "school", "in-di-vid-u-al", "🧑", ["multi"], "Each individual has different strengths."),
  makeWord(5, "initial", "The first letter of a name", "school", "i-ni-tial", "🔤", ["multi"], "Write your initial at the top of the page."),
  makeWord(5, "interrupt", "Stop something before it is finished", "action", "in-ter-rupt", "🛑", ["double_letter"], "It is rude to interrupt when someone is speaking."),
  makeWord(5, "investigate", "Study or examine carefully", "school", "in-ves-ti-gate", "🔍", ["multi"], "Scientists investigate new discoveries."),
  makeWord(5, "jealousy", "Feeling unhappy because someone has something you want", "feeling", "jeal-ous-y", "💚", ["multi"], "Jealousy can damage friendships."),
  makeWord(5, "language", "A system of words used to communicate", "school", "lan-guage", "🗣️", ["multi"], "She speaks three languages."),
  makeWord(5, "lightning", "A flash of light in a storm", "weather", "light-ning", "⚡", ["igh"], "Lightning struck the tall tree."),
  makeWord(5, "likelihood", "The chance that something will happen", "school", "like-li-hood", "📊", ["compound"], "There is a likelihood of rain today."),
  makeWord(5, "literature", "Written works such as books and poems", "school", "lit-er-a-ture", "📚", ["multi"], "She loved English literature."),
  makeWord(5, "maintenance", "Keeping something in good condition", "school", "main-te-nance", "🔧", ["multi"], "Regular maintenance keeps machines working."),
  makeWord(5, "mathematics", "The study of numbers and shapes", "school", "math-e-mat-ics", "➕", ["multi"], "Mathematics is used in everyday life."),
  makeWord(5, "measurement", "Finding the size of something", "school", "meas-ure-ment", "📏", ["multi"], "Use a ruler for accurate measurement."),
  makeWord(5, "memorable", "Easy to remember", "description", "mem-o-ra-ble", "⭐", ["multi"], "The trip to the museum was memorable."),
  makeWord(5, "miscellaneous", "A mix of different types", "school", "mis-cel-la-ne-ous", "📦", ["double_letter"], "The drawer was full of miscellaneous items."),
  makeWord(5, "mysterious", "Difficult to explain or understand", "description", "mys-te-ri-ous", "🔮", ["multi"], "A mysterious stranger arrived at the door."),
  makeWord(5, "neighbour", "Someone who lives near you", "people", "neigh-bour", "🏠", ["igh"], "Our neighbour brought us fresh vegetables."),
  makeWord(5, "noticeable", "Easy to see or recognise", "description", "no-tice-a-ble", "👁️", ["multi"], "There was a noticeable difference."),
  makeWord(5, "occasionally", "Sometimes but not often", "description", "oc-ca-sion-al-ly", "🔄", ["double_letter"], "She occasionally stayed for extra practice."),
  makeWord(5, "occupation", "A job or career", "school", "oc-cu-pa-tion", "💼", ["double_letter"], "Her occupation was a doctor."),
  makeWord(5, "opportunity", "A chance to do something", "school", "op-por-tu-ni-ty", "🌟", ["double_letter"], "This is a wonderful opportunity."),
  makeWord(5, "parliament", "The group that makes the laws of a country", "school", "par-lia-ment", "🏛️", ["multi"], "Parliament voted on the new bill."),
  makeWord(5, "particularly", "Especially or more than usual", "description", "par-tic-u-lar-ly", "⭐", ["multi"], "She was particularly good at spelling."),
  makeWord(5, "perception", "The way you see or understand something", "school", "per-cep-tion", "👁️", ["tion"], "Her perception of the problem was unique."),
  makeWord(5, "permanent", "Lasting forever", "description", "per-ma-nent", "♾️", ["multi"], "The painting made a permanent mark."),
  makeWord(5, "perseverance", "Continuing to try despite difficulty", "feeling", "per-se-ver-ance", "💪", ["multi"], "Perseverance is the key to success."),
  makeWord(5, "phenomenon", "An unusual observable event", "science", "phe-nom-e-non", "🌟", ["ph"], "The northern lights are a natural phenomenon."),
  makeWord(5, "physicist", "A scientist who studies physics", "science", "phys-i-cist", "⚛️", ["ph"], "The physicist discovered a new particle."),
  makeWord(5, "pollution", "Harmful substances in the environment", "science", "pol-lu-tion", "🏭", ["double_letter"], "Pollution harms wildlife and oceans."),
  makeWord(5, "population", "The number of people in a place", "school", "pop-u-la-tion", "👥", ["tion"], "The population of the city is growing."),
  makeWord(5, "possession", "Something you own", "school", "pos-ses-sion", "📦", ["double_letter"], "Take care of your possessions."),
  makeWord(5, "potential", "The ability to develop into something", "school", "po-ten-tial", "🌱", ["multi"], "She has great potential as a writer."),
  makeWord(5, "preparation", "Getting ready for something", "school", "prep-a-ra-tion", "📋", ["tion"], "Good preparation leads to success."),
  makeWord(5, "professional", "Relating to a skilled job", "school", "pro-fes-sion-al", "💼", ["double_letter"], "She was very professional in her presentation."),
  makeWord(5, "pronunciation", "The way a word is spoken", "school", "pro-nun-ci-a-tion", "🗣️", ["tion"], "The pronunciation of that word is tricky."),
  makeWord(5, "psychology", "The study of the mind", "school", "psy-chol-o-gy", "🧠", ["silent_p"], "She studied psychology at university."),
  makeWord(5, "punctuation", "Marks used in writing like commas and stops", "school", "punc-tu-a-tion", "📝", ["tion"], "Correct punctuation helps your writing."),
  makeWord(5, "qualification", "An exam or skill that proves your ability", "school", "qual-i-fi-ca-tion", "📜", ["tion"], "He earned a qualification in music."),
  makeWord(5, "questionnaire", "A set of written questions", "school", "ques-tion-naire", "📋", ["double_letter"], "Please complete the questionnaire."),
  makeWord(5, "realise", "Become aware of something", "thinking", "re-al-ise", "💡", ["multi"], "She did not realise she had won."),
  makeWord(5, "recommendation", "A suggestion that something is good", "school", "rec-om-men-da-tion", "⭐", ["double_letter"], "The doctor gave a recommendation."),
  makeWord(5, "refrigerator", "An appliance that keeps food cold", "home", "re-frig-er-a-tor", "🧊", ["multi"], "Store the milk in the refrigerator."),
  makeWord(5, "relationship", "A connection between people or things", "school", "re-la-tion-ship", "❤️", ["tion"], "They had a strong friendship and relationship."),
  makeWord(5, "relevant", "Closely connected to the topic", "school", "rel-e-vant", "🔗", ["multi"], "Make sure your answer is relevant."),
  makeWord(5, "remarkable", "Worth noticing or unusual", "description", "re-mark-a-ble", "🌟", ["multi"], "She made remarkable progress."),
  makeWord(5, "representative", "Someone who speaks for a group", "school", "rep-re-sen-ta-tive", "🗣️", ["multi"], "She was the class representative."),
  makeWord(5, "respiratory", "Relating to breathing", "science", "res-pi-ra-to-ry", "🫁", ["multi"], "The respiratory system includes the lungs."),
  makeWord(5, "responsible", "Having a duty to do something", "school", "re-spon-si-ble", "✅", ["multi"], "She was responsible for locking up."),
  makeWord(5, "rhyme", "Words that sound similar at the end", "school", "rhyme", "🎵", ["silent_h"], "Can you find a rhyme for the word cat?"),
  makeWord(5, "rhythm", "A regular pattern of sounds", "music", "rhythm", "🥁", ["silent_h"], "The rhythm of the music made us dance."),
  makeWord(5, "satisfactory", "Good enough to meet expectations", "school", "sat-is-fac-to-ry", "✅", ["multi"], "Her work was satisfactory but could improve."),
  makeWord(5, "scenery", "The natural landscape", "nature", "scen-er-y", "🏞️", ["silent_c"], "The mountain scenery was breathtaking."),
  makeWord(5, "scholarship", "Money given to help pay for education", "school", "schol-ar-ship", "🎓", ["multi"], "She won a scholarship to university."),
  makeWord(5, "scientific", "Related to science", "science", "sci-en-tif-ic", "🔬", ["multi"], "The scientific experiment was a success."),
  makeWord(5, "scissors", "A tool with two blades for cutting", "object", "scis-sors", "✂️", ["silent_c"], "Use the scissors carefully."),
  makeWord(5, "sentence", "A group of words that makes complete sense", "school", "sen-tence", "📝", ["multi"], "Every sentence begins with a capital letter."),
  makeWord(5, "separately", "Apart from each other", "description", "sep-a-rate-ly", "↔️", ["multi"], "Keep the red and blue pens separately."),
  makeWord(5, "significance", "The importance or meaning of something", "school", "sig-nif-i-cance", "⭐", ["multi"], "The significance of the discovery was huge."),
  makeWord(5, "simultaneous", "Happening at the same time", "school", "si-mul-ta-ne-ous", "⏱️", ["multi"], "The two events were simultaneous."),
  makeWord(5, "sophisticated", "Highly developed or complex", "description", "so-phis-ti-cat-ed", "🎩", ["ph"], "She had a sophisticated understanding."),
  makeWord(5, "specifically", "In a precise or exact way", "description", "spe-cif-i-cal-ly", "🎯", ["multi"], "I specifically asked for no onions."),
  makeWord(5, "spontaneous", "Done without planning", "description", "spon-ta-ne-ous", "🎉", ["multi"], "The party was a spontaneous idea."),
  makeWord(5, "straightforward", "Simple and easy to understand", "description", "straight-for-ward", "➡️", ["compound"], "The instructions were straightforward."),
  makeWord(5, "strengthen", "Make something stronger", "action", "strength-en", "💪", ["multi"], "Exercise can strengthen your muscles."),
  makeWord(5, "structure", "The way something is built or organised", "school", "struc-ture", "🏗️", ["multi"], "The structure of a sentence has a subject and verb."),
  makeWord(5, "subconscious", "Part of the mind below awareness", "science", "sub-con-scious", "🧠", ["multi"], "Fear can be subconscious."),
  makeWord(5, "substantial", "Large in size or amount", "description", "sub-stan-tial", "📦", ["multi"], "She made a substantial improvement."),
  makeWord(5, "sufficient", "Enough", "description", "suf-fi-cient", "✅", ["double_letter"], "There was sufficient food for everyone."),
  makeWord(5, "suggest", "Put an idea forward", "action", "sug-gest", "💡", ["double_letter"], "Can you suggest a better solution?"),
  makeWord(5, "surroundings", "Everything around you", "school", "sur-round-ings", "🌍", ["double_letter"], "She admired her beautiful surroundings."),
  makeWord(5, "suspicious", "Feeling that something is wrong", "feeling", "sus-pi-cious", "🕵️", ["multi"], "She felt suspicious about the strange noise."),
  makeWord(5, "synonym", "A word with the same meaning as another", "school", "syn-o-nym", "🔄", ["multi"], "Happy is a synonym for joyful."),
  makeWord(5, "technology", "The use of scientific knowledge", "school", "tech-nol-o-gy", "💻", ["multi"], "Technology has changed how we learn."),
  makeWord(5, "thorough", "Complete and careful", "description", "thor-ough", "✅", ["ough"], "She did a thorough job of cleaning."),
  makeWord(5, "tragedy", "A very sad event", "school", "trag-e-dy", "😢", ["multi"], "The play ended in tragedy."),
  makeWord(5, "transparent", "You can see through it", "description", "trans-par-ent", "🪟", ["multi"], "Glass is transparent."),
  makeWord(5, "triumph", "A great victory or success", "feeling", "tri-umph", "🏆", ["ph"], "Winning the final was a great triumph."),
  makeWord(5, "unanimous", "Everyone agreeing", "school", "u-nan-i-mous", "🤝", ["multi"], "The class was unanimous in their decision."),
  makeWord(5, "unfortunately", "Sadly or unluckily", "description", "un-for-tu-nate-ly", "😔", ["multi"], "Unfortunately the match was cancelled."),
  makeWord(5, "unique", "One of a kind", "description", "u-nique", "🌟", ["multi"], "Each snowflake is unique."),
  makeWord(5, "unnecessary", "Not needed", "description", "un-nec-es-sa-ry", "🚫", ["double_letter"], "The extra detail was unnecessary."),
  makeWord(5, "versatile", "Able to do many different things", "description", "ver-sa-tile", "🔄", ["multi"], "A versatile actor can play any role."),
  makeWord(5, "vocabulary", "All the words you know", "school", "vo-cab-u-la-ry", "📖", ["multi"], "Reading improves your vocabulary."),
  makeWord(5, "voluntary", "Done by choice without being paid", "school", "vol-un-ta-ry", "🤝", ["multi"], "She did voluntary work at the shelter."),
  makeWord(5, "yacht", "A large sailing boat", "transport", "yacht", "⛵", ["silent_ch"], "We sailed across the bay on a yacht."),
];

export const SPELLING_WORD_BANK: SpellingWordBankEntry[] = [...L1, ...L2, ...L3, ...L4, ...L5];
