import { LOCKED_PROMISE } from "@/lib/policies/locked-facts";

export type KnowledgeArticle = {
  id: string;
  title: string;
  summary: string;
  body?: string[];
  keywords: string[];
  audience: "Parent" | "Student" | "School Admin" | "Teacher" | "Platform Admin";
  category:
    | "Getting started"
    | "Short Learning"
    | "AI Tutor"
    | "Human tutor support"
    | "Subscription and billing"
    | "Parent portal"
    | "Student portal"
    | "School and tutor support"
    | "Safety and privacy"
    | "FAQs";
  href?: string;
};

export const KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: "what-is-starliz",
    title: "What is StarLiz?",
    category: "Getting started",
    audience: "Parent",
    keywords: ["starliz", "overview", "platform"],
    summary: "StarLiz Academy is a UK learning platform with Day School timetable learning and parent-booked Short Learning after hours.",
    body: [
      "StarLiz Academy helps children learn with AI-first teaching and optional human support when tutors are on shift and available.",
      LOCKED_PROMISE,
    ],
  },
  {
    id: "what-is-day-school",
    title: "What is Day School?",
    category: "Getting started",
    audience: "Parent",
    keywords: ["day school", "timetable", "attendance"],
    summary: "Day School is fixed-timetable, school-led learning during the school day. Parents do not book Day School periods.",
  },
  {
    id: "what-is-short-learning",
    title: "What is Short Learning?",
    category: "Getting started",
    audience: "Parent",
    keywords: ["short learning", "after hours", "booking"],
    summary: "Short Learning is parent-booked, AI-led learning outside Day School hours — not a named private tutor booking.",
    href: "/short-learning",
  },
  {
    id: "day-school-vs-short-learning",
    title: "How Day School and Short Learning differ",
    category: "Getting started",
    audience: "Parent",
    keywords: ["difference", "day school", "short learning"],
    summary:
      "Day School follows a fixed school timetable with attendance tracked against scheduled periods. Short Learning uses parent-booked 90/120-minute sessions outside school hours.",
  },
  {
    id: "create-manage-account",
    title: "How to create and manage an account",
    category: "Getting started",
    audience: "Parent",
    keywords: ["account", "signup", "login"],
    summary: "Sign up from the public site, verify access, then manage children from the parent portal.",
    href: "/auth/signup",
  },
  {
    id: "which-portal",
    title: "Which portal should I use?",
    category: "Getting started",
    audience: "Parent",
    keywords: ["portal", "parent", "student", "teacher", "admin"],
    summary:
      "Parents use /parent. Students use /student. Teachers use /teacher. School operators use /school-admin. Platform operators use /admin.",
  },
  {
    id: "how-to-book",
    title: "How to book Short Learning",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["book", "booking", "parent"],
    summary: "Open parent Short Learning, choose an entitled child, pick a 90 or 120-minute slot, and confirm the AI-led honesty statement.",
    href: "/parent/short-learning",
  },
  {
    id: "available-days-times",
    title: "Available days and times",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["times", "weekday", "weekend", "hours"],
    summary: "Weekdays 16:00–20:00. Weekends 09:00–18:00. Starts every 30 minutes where capacity permits.",
  },
  {
    id: "session-lengths",
    title: "90-minute versus 120-minute sessions",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["90", "120", "duration"],
    summary: "You can book 90 or 120 minutes. Both are AI-led Short Learning sessions under the same support promise.",
  },
  {
    id: "how-far-ahead",
    title: "How far ahead bookings open",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["advance", "7 days", "14 days"],
    summary: "Weekday bookings open 7 days ahead. Weekend bookings open 14 days ahead.",
  },
  {
    id: "booking-deadlines",
    title: "Booking deadlines",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["deadline", "12:00", "thursday"],
    summary: "Weekday standard deadline: 12:00 same day. Weekend standard deadline: Thursday 18:00.",
  },
  {
    id: "late-bookings",
    title: "Late bookings",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["late", "capacity"],
    summary: "After the standard deadline, late booking is allowed only where existing capacity still permits.",
  },
  {
    id: "cancelling-booking",
    title: "Cancelling a booking",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["cancel", "cancellation"],
    summary: "Cancel from the parent Short Learning area within free-cancellation windows. There is no cancellation fee.",
  },
  {
    id: "no-cancellation-fees",
    title: "Why there is no cancellation fee",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["fee", "refund", "subscription"],
    summary:
      "Short Learning access is covered by monthly subscription. Cancelling a session does not create a booking charge or cancellation fee.",
  },
  {
    id: "booking-confirmation",
    title: "Booking confirmation",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["confirm", "confirmation"],
    summary: "Bookings appear in the parent portal. You may be asked to confirm intention to attend before the session.",
  },
  {
    id: "joining-session",
    title: "Joining a session",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["join", "start", "learn"],
    summary: "Your child joins from the student Short Learning learn path at the booked time. AI teaching starts with the session.",
  },
  {
    id: "no-shows-limits",
    title: "No-shows and booking limits",
    category: "Short Learning",
    audience: "Parent",
    keywords: ["no-show", "reliability", "limits"],
    summary:
      "Repeated no-shows may reduce booking limits, shorten advance windows, require extra confirmations, or temporarily restrict booking — not financial penalties.",
  },
  {
    id: "ai-how-teaches",
    title: "How the AI Tutor teaches",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["ai", "teach", "adapt"],
    summary: "The AI Tutor guides practice, explains concepts and adapts to the child's activity during the session.",
    href: "/ai-use",
  },
  {
    id: "ai-help",
    title: "What help the AI can provide",
    category: "AI Tutor",
    audience: "Student",
    keywords: ["help", "stuck", "explain"],
    summary: "Ask the AI Tutor when you are stuck. It can explain steps and give practice — it is not a human friend chat.",
  },
  {
    id: "ai-progress",
    title: "How progress is adapted",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["progress", "adaptive"],
    summary: "AI adapts practice from learner activity so children can keep moving through lesson stages.",
  },
  {
    id: "ai-when-stuck",
    title: "What happens when a child is stuck",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["stuck", "support"],
    summary:
      "AI keeps helping. If eligibility is met and a tutor is on shift and available, human support may join. Otherwise learning continues with AI.",
  },
  {
    id: "ai-monitored",
    title: "How AI activity is monitored",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["monitor", "quality", "safety"],
    summary: "AI activity may be monitored for quality and safety. Concerns can be reported to support.",
  },
  {
    id: "ai-limits",
    title: "AI limitations",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["limitations", "disclaimer"],
    summary: "AI is not emergency care or clinical advice, and it does not guarantee a human tutor will join.",
  },
  {
    id: "report-ai-concern",
    title: "How to report an AI concern",
    category: "AI Tutor",
    audience: "Parent",
    keywords: ["report", "concern", "ai"],
    summary: "Email support@starlizacademy.com. If a child may be at risk, also use safeguarding channels.",
  },
  {
    id: "human-when-available",
    title: "When human support may be available",
    category: "Human tutor support",
    audience: "Parent",
    keywords: ["human", "tutor", "available"],
    summary: LOCKED_PROMISE,
  },
  {
    id: "human-not-guaranteed",
    title: "Why human support is not guaranteed",
    category: "Human tutor support",
    audience: "Parent",
    keywords: ["guaranteed", "safety net"],
    summary: "Human support depends on published shifts and live availability. AI teaching remains guaranteed for the session.",
  },
  {
    id: "not-private-tutor",
    title: "Why a booking is not a private tutor booking",
    category: "Human tutor support",
    audience: "Parent",
    keywords: ["private", "named", "1:1"],
    summary: "You book learning time with AI teaching. You do not reserve a named tutor for a private 1:1 session.",
  },
  {
    id: "no-tutor-available",
    title: "What happens when no tutor is available",
    category: "Human tutor support",
    audience: "Parent",
    keywords: ["offline", "continue", "ai"],
    summary: "The child continues with AI and is not parked waiting for an offline tutor.",
  },
  {
    id: "how-shifts-work",
    title: "How tutor shifts work",
    category: "Human tutor support",
    audience: "Teacher",
    keywords: ["shift", "heartbeat", "available"],
    summary: "Login does not mean available. Availability requires on-shift status, fresh heartbeat and active access.",
  },
  {
    id: "what-tutors-see",
    title: "What tutors can see",
    category: "Human tutor support",
    audience: "Teacher",
    keywords: ["visibility", "session", "context"],
    summary: "On-shift tutors helping a child may see the session context needed to support learning.",
  },
  {
    id: "during-human-support",
    title: "What happens during a human-support session",
    category: "Human tutor support",
    audience: "Parent",
    keywords: ["session", "support", "help"],
    summary: "A tutor may join an active learning session to help when eligible. This is learning support, not a private social chat.",
  },
  {
    id: "subscription-includes",
    title: "What the monthly subscription includes",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["subscription", "monthly", "includes"],
    summary: "Eligible plans cover Short Learning booking access. Cancel booking ≠ cancel subscription. See Subscription Terms for cooling-off, end-of-period cancel and payment grace.",
    href: "/policies/subscription-terms",
  },
  {
    id: "bookings-extra-cost",
    title: "Whether bookings cost extra",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["extra", "fee", "booking"],
    summary: "There is no per-booking fee for standard Short Learning sessions.",
  },
  {
    id: "cancellation-charges",
    title: "Cancellation charges",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["cancellation", "charge", "fee"],
    summary:
      "There is no cancellation fee and no late-cancellation charge on Short Learning bookings. Subscription cancel is separate and is done in the Parent Portal.",
  },
  {
    id: "refunds-help",
    title: "Refunds",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["refund", "cooling-off", "pro-rata", "goodwill"],
    summary:
      "No automatic pro-rata refund on mid-period cancel. Booking cancel and unused sessions are not refunds. Human tutor unavailability is not a refund. Cooling-off and rare goodwill refunds follow the Refund Policy.",
    href: "/policies/refund-policy",
  },
  {
    id: "no-refund-unused-sessions",
    title: "Unused sessions are not refundable",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["unused", "sessions", "attendance"],
    summary:
      "The subscription buys access, not guaranteed attendance. Unused Short Learning sessions do not create a refund.",
    href: "/policies/refund-policy",
  },
  {
    id: "no-refund-human-unavailable",
    title: "Human tutor unavailable — is that a refund?",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["human", "tutor", "refund"],
    summary:
      "No. AI teaching is guaranteed; human support is a safety net when available. Tutor unavailability is not a refund event when AI learning worked as described.",
    href: "/policies/refund-policy",
  },
  {
    id: "failed-payment",
    title: "Failed payment",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["payment", "failed", "grace"],
    summary:
      "If payment fails, there is a 7-day grace period with notices and retries. Access and bookings continue during grace. After day 7, Short Learning entitlement suspends until payment succeeds; history stays intact.",
  },
  {
    id: "cancel-subscription",
    title: "Subscription cancellation",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["cancel subscription", "billing period", "parent portal"],
    summary:
      "Cancel booking is not cancel subscription. Cancel in the Parent Portal (self-service). Access continues to the end of the current billing period; renewals then stop. Support can help if needed.",
    href: "/policies/subscription-terms",
  },
  {
    id: "access-after-ends",
    title: "Access after subscription ends",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["ended", "access", "expiry"],
    summary:
      "After the billing period ends: no new Short Learning bookings or sessions. Historical reports remain under the retention policy. Day School continues where provided by the school, not the parent subscription.",
  },
  {
    id: "cooling-off",
    title: "14-day cooling-off for new subscriptions",
    category: "Subscription and billing",
    audience: "Parent",
    keywords: ["cooling-off", "14 days", "distance selling"],
    summary:
      "New consumer online subscriptions have a 14-day cooling-off period with immediate start where you choose digital access now. Exact effect of use on any refund is confirmed in final legal wording.",
    href: "/policies/subscription-terms",
  },
  {
    id: "managing-children",
    title: "Managing children",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["children", "profiles"],
    summary: "Add and select children from the parent profiles area before booking or viewing progress.",
  },
  {
    id: "upcoming-bookings",
    title: "Upcoming bookings",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["upcoming", "bookings"],
    summary: "View and manage upcoming Short Learning bookings in the parent Short Learning area.",
  },
  {
    id: "confirming-attendance",
    title: "Confirming intention to attend",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["confirm", "attend"],
    summary: "When asked, confirm that your child still intends to attend so capacity stays accurate.",
  },
  {
    id: "parent-cancelling",
    title: "Cancelling from the parent portal",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["cancel", "parent"],
    summary: "Use the cancel action on a booking. There is no cancellation fee.",
  },
  {
    id: "viewing-progress",
    title: "Viewing progress",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["progress"],
    summary: "Progress views show learning activity for linked children within your parent access.",
  },
  {
    id: "viewing-reports",
    title: "Viewing reports",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["reports"],
    summary: "Learning reports are available to authorised parents for their children.",
  },
  {
    id: "attendance-labels",
    title: "Understanding attendance and no-show labels",
    category: "Parent portal",
    audience: "Parent",
    keywords: ["no-show", "attended", "cancelled"],
    summary: "Statuses such as Booked, Confirmed, Attended, Completed, Cancelled, Late cancelled, No-show and Expired track operations — not fees.",
  },
  {
    id: "student-day-school",
    title: "Entering Day School",
    category: "Student portal",
    audience: "Student",
    keywords: ["today", "day school"],
    summary: "Open Day School / Today from the student portal to follow your school timetable.",
  },
  {
    id: "student-short-learning",
    title: "Entering Short Learning",
    category: "Student portal",
    audience: "Student",
    keywords: ["short learning", "join"],
    summary: "When a parent books a session, join from Short Learning at the scheduled time.",
  },
  {
    id: "student-ai-tutor",
    title: "Using AI Tutor",
    category: "Student portal",
    audience: "Student",
    keywords: ["ai tutor"],
    summary: "The AI Tutor teaches during your lesson. Ask for help when you need it.",
  },
  {
    id: "student-ask-help",
    title: "Asking for help",
    category: "Student portal",
    audience: "Student",
    keywords: ["help"],
    summary: "Start with the AI Tutor. A human may join only if one is on shift and available.",
  },
  {
    id: "student-human-support",
    title: "Human support for students",
    category: "Student portal",
    audience: "Student",
    keywords: ["human", "tutor"],
    summary: "Human support is extra help when available. If nobody is free, keep learning with AI.",
  },
  {
    id: "student-progress-stages",
    title: "Progress and lesson stages",
    category: "Student portal",
    audience: "Student",
    keywords: ["stages", "progress"],
    summary: "Move through lesson stages with AI guidance. Your progress is saved for your parent and school to see where allowed.",
  },
  {
    id: "student-stay-safe",
    title: "Staying safe online",
    category: "Student portal",
    audience: "Student",
    keywords: ["safe", "online"],
    summary: "Be kind, stay on learning tasks, and tell a trusted adult if something feels wrong.",
  },
  {
    id: "school-admin-access",
    title: "School Admin access",
    category: "School and tutor support",
    audience: "School Admin",
    keywords: ["school-admin", "portal"],
    summary: "School operators use /school-admin for Short Learning ops, shifts, coverage and reliability — separate from Day School attendance.",
    href: "/policies/school-admin-ops",
  },
  {
    id: "teacher-portal",
    title: "Teacher portal",
    category: "School and tutor support",
    audience: "Teacher",
    keywords: ["teacher", "portal"],
    summary: "Teachers use /teacher for classroom and support tools. Availability still requires a published shift.",
  },
  {
    id: "tutor-portal",
    title: "Tutor portal and availability",
    category: "School and tutor support",
    audience: "Teacher",
    keywords: ["availability", "shift"],
    summary: "Off-shift tutors can see upcoming shifts and history but cannot accept students or claim cases.",
  },
  {
    id: "shift-status",
    title: "Shift status",
    category: "School and tutor support",
    audience: "Teacher",
    keywords: ["status", "on_shift", "scheduled"],
    summary: "Shift status and fresh heartbeat control whether you can become available.",
  },
  {
    id: "support-outcomes",
    title: "Support outcomes",
    category: "School and tutor support",
    audience: "Teacher",
    keywords: ["outcomes", "support"],
    summary: "Record support outcomes accurately after helping a learner.",
  },
  {
    id: "safeguarding-concerns-staff",
    title: "Safeguarding concerns",
    category: "School and tutor support",
    audience: "School Admin",
    keywords: ["safeguarding", "dsl"],
    summary: "Use safeguarding workflows and school DSL routes. Do not treat the tutor queue as safeguarding.",
    href: "/safeguarding-policy",
  },
  {
    id: "child-safety",
    title: "Child safety",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["safety", "child"],
    summary: "Child welfare comes first. Report concerns promptly to safeguarding channels.",
    href: "/safeguarding-policy",
  },
  {
    id: "data-protection-help",
    title: "Data protection",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["gdpr", "privacy", "controller", "school"],
    summary:
      "When a school provides StarLiz, the school is normally controller for Day School records and StarLiz is processor. When you buy Short Learning directly, StarLiz is normally controller for that service. See Privacy and Data Protection Policies.",
    href: "/privacy",
  },
  {
    id: "who-controls-my-data",
    title: "Who is the data controller for my child's records?",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["controller", "processor", "school", "short learning"],
    summary:
      "Day School and school-directed records: normally the school. Direct Short Learning subscription and bookings: normally StarLiz. Mixed requests are split and explained. Full mapping is in the Data Protection Policy.",
    href: "/policies/data-protection",
  },
  {
    id: "data-retention-help",
    title: "How long we keep learning and booking records",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["retention", "delete", "anonymise"],
    summary:
      "Examples: Short Learning bookings and progress typically up to 3 years; detailed AI conversations 12 months; closed profiles 24 months; financial records 6 years from year-end. Safeguarding records follow a separate schedule.",
    href: "/data-retention",
  },
  {
    id: "cookies-help",
    title: "Cookies",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["cookies"],
    summary: "Essential cookies keep you signed in. See the Cookie Policy for details.",
    href: "/cookies",
  },
  {
    id: "ai-transparency-help",
    title: "AI transparency",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["ai", "transparency"],
    summary: LOCKED_PROMISE,
    href: "/ai-use",
  },
  {
    id: "report-inappropriate",
    title: "Reporting inappropriate content",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["report", "inappropriate"],
    summary: "Contact support@starlizacademy.com or safeguarding@starlizacademy.com for welfare concerns.",
  },
  {
    id: "complaints-help",
    title: "Complaints",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["complaint", "sla", "response time", "working day"],
    summary:
      "Email support@starlizacademy.com. Ordinary complaints: acknowledge within 2 working days; substantive response within 10. Complex: up to 20 working days. Safeguarding is immediate and outside these SLAs.",
    body: [
      "Preferred commercial stance pending solicitor review — published service targets, not guaranteed remedies.",
      "Acknowledge ordinary complaints within 2 working days; substantive response within 10 working days.",
      "Complex or escalated: within 20 working days, with an interim update by day 10 if still open.",
      "Urgent account-access or payment-blocking: acknowledge within 1 working day.",
      "Child welfare concerns: safeguarding@starlizacademy.com immediately (or emergency services if immediate danger).",
    ],
    href: "/policies/complaints",
  },
  {
    id: "complaint-response-times",
    title: "Complaint response times",
    category: "FAQs",
    audience: "Parent",
    keywords: ["complaint", "2 working days", "10 working days"],
    summary:
      "2 working days to acknowledge; 10 for a substantive response; up to 20 for complex cases. Full detail is in the Complaints Procedure.",
    href: "/policies/complaints",
  },
  {
    id: "accessibility-help",
    title: "Accessibility support",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["accessibility", "wcag", "screen reader", "keyboard"],
    summary:
      "StarLiz targets WCAG 2.2 Level AA and improves accessibility continuously. Report barriers to support@starlizacademy.com with the page URL. We do not claim full compliance until independently audited.",
    href: "/policies/accessibility",
  },
  {
    id: "accessibility-target",
    title: "What accessibility standard does StarLiz aim for?",
    category: "Safety and privacy",
    audience: "Parent",
    keywords: ["wcag", "2.2", "aa"],
    summary:
      "WCAG 2.2 Level AA is the target. The Accessibility Statement explains commitments such as keyboard access, contrast, labels and focus indicators.",
    href: "/policies/accessibility",
  },
  {
    id: "faq-hub",
    title: "Frequently asked questions",
    category: "FAQs",
    audience: "Parent",
    keywords: ["faq"],
    summary: "Quick answers about Day School, Short Learning, booking and AI-led sessions.",
    href: "/faq",
  },
  {
    id: "policies-hub",
    title: "Full policies library",
    category: "FAQs",
    audience: "Parent",
    keywords: ["policies"],
    summary:
      "Browse public legal and product policy drafts. Staff handbooks are authenticated-only for school and platform operators.",
    href: "/policies",
  },
];
