import { buildPolicy, s } from "../build";
import type { PolicyDocument } from "../types";

/** Phase 6 draft set — aligned to shipped product behaviour. */
export const LEGAL_POLICIES: PolicyDocument[] = [
  buildPolicy({
    id: "terms",
    slug: "terms",
    title: "Terms and Conditions",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Set the rules for using StarLiz Academy websites, apps and learning services.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Set the rules for using StarLiz Academy websites, apps and learning services.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/terms",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    relatedDocumentIds: ["privacy","subscription-terms","booking-cancellation"],
    sections: [
      s("1. About these terms",
        "These Terms govern access to StarLiz Academy. Draft for legal review — not formal legal advice.",
      ),
      s("2. Learning modes",
        "Day School follows a fixed school timetable with school-led attendance.",
        "Day School is teacher-led and AI-first during the school day.",
        "Parents do not book Day School periods.",
        "Day School uses SchoolDayLesson records and must not be confused with Short Learning bookings.",
        "Short Learning is parent-booked learning time outside Day School hours.",
        "Sessions are AI-led and are not named-tutor bookings.",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Session lengths are 90 or 120 minutes, starting every 30 minutes where capacity permits.",
        "Weekday window: 16:00–20:00. Weekend window: 09:00–18:00.",
        "Short Learning uses SchoolLearningWindow capacity and StudentLearningBooking records.",
      ),
      s("3. AI and human support",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("4. Subscriptions and bookings",
        "Weekday bookings open 7 days ahead. Standard deadline: 12:00 same day. School admin finalises tutor shifts by 14:00. Late booking is allowed only where existing capacity permits. Free cancellation until 2 hours before the session.",
        "Weekend bookings open 14 days ahead. Standard deadline: Thursday 18:00. School admin finalises tutor shifts by Friday 12:00. Late booking only where capacity permits. Free cancellation until 18:00 the previous day.",
        "There is no per-booking fee, no cancellation fee, no late-cancellation charge, and no private-tutor fee. The monthly subscription covers Short Learning access.",
        "Cancellations and no-shows affect operations and reliability tracking only. They are not financial penalties.",
        "Booking statuses include: Booked, Confirmed, Attended, Completed, Cancelled, Late cancelled, No-show, Expired.",
        "Cancel booking is not cancel subscription. See Subscription Terms for cooling-off, end-of-period cancellation, Parent Portal self-service cancel, and the 7-day failed-payment grace period (preferred commercial stance pending solicitor review).",
      ),
      s("5. Acceptable use and enforcement",
        "Do not misuse the platform, bypass security, or put children at risk. We may suspend accounts that breach these terms.",
      ),
      s("6. Complaints",
        "Service complaints: email support@starlizacademy.com with your account email and issue details. See the Complaints Procedure for response-time targets.",
        "Preferred commercial stance pending solicitor review: acknowledge ordinary complaints within 2 working days; substantive response within 10 working days; complex or escalated matters within 20 working days (with an interim update by day 10 if still open); urgent account-access or payment-blocking issues acknowledged within 1 working day.",
        "Child welfare concerns: safeguarding@starlizacademy.com (or emergency services if immediate danger). Safeguarding is outside ordinary complaint SLAs.",
        "These timelines are service targets, not guarantees of a particular remedy, refund or human-tutor assignment.",
      ),
    ],
  }),
  buildPolicy({
    id: "privacy",
    slug: "privacy",
    title: "Privacy Policy",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Explain how StarLiz Academy processes personal data under UK GDPR, including school and direct-to-parent roles.",
    scope: "Parents, carers, students, school staff and other users of StarLiz Academy services in the UK launch scope.",
    summary: "What we process, controller/processor roles by purpose, children's data, rights routing, and contacts — preferred governance position pending solicitor/DPO review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/privacy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["cookies","data-retention","data-protection","ai-use"],
    sections: [
      s("1. Who we are",
        "StarLiz Academy operates learning platforms for families and schools. Draft for legal review — not formal legal advice.",
        "Contact for privacy queries: support@starlizacademy.com.",
      ),
      s("2. Controllers and processors (summary)",
        "Preferred data-governance position pending solicitor and DPO review.",
        "When a school provides StarLiz, the school or academy trust will normally be the data controller for pupil, timetable, attendance and school-directed learning records, and StarLiz will process that information on the school's documented instructions.",
        "When a parent buys Short Learning directly from StarLiz, StarLiz is normally the data controller for the subscription, booking and learning-service information needed to provide that service.",
        "StarLiz may also act as an independent controller for limited purposes such as account security, legal compliance, fraud prevention, safeguarding incidents and operating its direct consumer services.",
        "Roles are determined by processing purpose. Full mapping is in the Data Protection Policy.",
      ),
      s("3. Data we process",
        "Account and profile data; child learning data including Day School and Short Learning activity; support and safeguarding records where raised; technical logs; payment and subscription metadata via payment providers (we do not store full card numbers on StarLiz servers).",
      ),
      s("4. Why we process data",
        "To provide Day School and Short Learning services; personalise AI tutoring and report progress to authorised parents and school staff; operate subscriptions and booking access; keep children safer online; meet legal obligations; and defend against misuse.",
        "We do not sell children's personal data.",
        "Identifiable school pupil data is not used for StarLiz independent product development unless the school contract expressly permits it and the role, lawful basis and transparency requirements are met. Irreversibly anonymised analytics may be used for service improvement.",
      ),
      s("5. Children's data and sharing",
        "Parents should only create child profiles for children they are authorised to manage.",
        "Schools may access school-scoped learner data for enrolled students according to their role.",
        "We share data with processors such as hosting, email, AI and payment providers under contracts. Suppliers are labelled according to the real contract role, not automatically as processors.",
      ),
      s("6. Your rights and how requests are routed",
        "UK GDPR rights may include access, rectification, erasure, restriction, objection and complaint to the ICO, subject to exemptions.",
        "For school-controlled Day School records, StarLiz logs the request, verifies enough information to route safely, promptly refers it to the school, and assists the school under the data-processing agreement. StarLiz does not independently decide the school's response unless legally required.",
        "For StarLiz-controlled Short Learning and subscription data, StarLiz handles the request directly.",
        "Mixed requests are split internally; we explain which organisation is handling each part.",
        "Contact support@starlizacademy.com. Safeguarding retention or legal holds may limit erasure in some cases.",
      ),
      s("7. Retention, cookies and AI",
        "See the Data Retention Policy, Cookie Policy and AI Use and Transparency Policy.",
      ),
    ],
  }),
  buildPolicy({
    id: "cookies",
    slug: "cookies",
    title: "Cookie Policy",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Describe cookies and similar technologies used on StarLiz Academy sites.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Describe cookies and similar technologies used on StarLiz Academy sites.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/cookies",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Describe cookies and similar technologies used on StarLiz Academy sites.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Essential cookies support authentication and security.",
        "Functional cookies may store preferences.",
        "Analytics cookies are optional where enabled.",
        "Blocking essential cookies may break login or booking.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "subscription-terms",
    slug: "subscription-terms",
    title: "Subscription Terms",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Explain what a monthly subscription includes and how access, cooling-off, cancellation and failed payments work.",
    scope: "Parents and carers purchasing or managing StarLiz Academy consumer subscriptions for Short Learning access and related plan features in the UK launch scope.",
    summary: "Subscription covers Short Learning access; booking cancel ≠ subscription cancel; end-of-period cancel; 14-day cooling-off and 7-day payment grace as preferred commercial stance pending solicitor review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/subscription-terms",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["refund-policy","booking-cancellation","terms"],
    sections: [
      s("1. Preferred commercial stance",
        "Preferred commercial stance pending solicitor review — not formal legal advice. Final statutory wording will be confirmed in legal review.",
      ),
      s("2. What the subscription includes",
        "Eligible monthly subscriptions cover Short Learning booking access for entitled children, subject to capacity and booking rules — no per-booking fee.",
        "No cancellation fee, late-cancellation charge, or private-tutor fee.",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Day School access for school-enrolled learners is governed by the school's arrangement and is separate from the parent Short Learning subscription.",
      ),
      s("3. Cooling-off (14 days)",
        "For new consumer subscriptions purchased online, StarLiz applies a 14-day cooling-off period in line with standard UK distance-selling expectations, subject to the parent agreeing that digital services may begin immediately.",
        "The subscription starts immediately when purchased.",
        "The parent may request cancellation within 14 days.",
        "If the parent has not used the service, a refund can be considered under the final legal wording.",
        "If the parent has chosen immediate access and has already used the digital learning service, the final legal wording will explain how that affects the cooling-off right. Exact statutory wording is confirmed during solicitor review.",
      ),
      s("4. Subscription cancellation (end of billing period)",
        "Cancelling a subscription means the subscription remains active until the end of the current billing period. It does not end immediately.",
        "Example: if the subscription renews on 20 August and the parent cancels on 5 August, access continues until 20 August and no further renewal occurs.",
        "During the remaining paid period: existing bookings remain valid; new bookings are still allowed while the subscription is active; reports remain accessible; the child continues learning.",
        "Once the subscription expires: no new Short Learning bookings; no new Short Learning sessions; historical reports remain available according to the Data Retention Policy; Day School access continues where provided through the school rather than the subscription.",
        "There is no automatic pro-rata refund for unused days in the current billing period. See the Refund Policy for goodwill exceptions and cooling-off.",
      ),
      s("5. Booking vs subscription",
        "Cancel booking is not cancel subscription. These actions are completely separate.",
        "Cancelling a Short Learning booking: no cancellation fee, no booking refund, and no subscription change.",
        "Cancelling a subscription: future renewals stop; the current billing period continues; existing bookings are not cancelled before expiry; there are no booking penalties.",
      ),
      s("6. How parents cancel",
        "Parents can always cancel a subscription inside the Parent Portal (self-service).",
        "Support can assist where needed (Need help? Contact Support), but there is no phone-call requirement, no contact-us-only barrier, and no hidden cancellation process.",
      ),
      s("7. Failed payments (7-day grace)",
        "If a renewal payment fails, StarLiz applies a 7-day grace period with email notice and payment retries.",
        "During the grace period: existing bookings remain; new bookings can continue; access continues.",
        "If payment is still not received after day 7, Short Learning entitlement is suspended: no new Short Learning bookings; upcoming Short Learning bookings become unavailable until payment is resolved; previous learning history remains intact.",
        "Access is restored immediately after successful payment.",
      ),
      s("8. Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "booking-cancellation",
    slug: "booking-cancellation",
    title: "Booking and Cancellation Policy",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Describe Short Learning booking windows, deadlines and free cancellation.",
    scope: "Parent-booked Short Learning only. Does not apply to Day School timetable periods.",
    summary: "Describe Short Learning booking windows, deadlines and free cancellation.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/booking-cancellation",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Describe Short Learning booking windows, deadlines and free cancellation.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Weekday bookings open 7 days ahead. Standard deadline: 12:00 same day. School admin finalises tutor shifts by 14:00. Late booking is allowed only where existing capacity permits. Free cancellation until 2 hours before the session.",
        "Weekend bookings open 14 days ahead. Standard deadline: Thursday 18:00. School admin finalises tutor shifts by Friday 12:00. Late booking only where capacity permits. Free cancellation until 18:00 the previous day.",
        "There is no per-booking fee, no cancellation fee, no late-cancellation charge, and no private-tutor fee. The monthly subscription covers Short Learning access.",
        "Cancellations and no-shows affect operations and reliability tracking only. They are not financial penalties.",
        "Booking statuses include: Booked, Confirmed, Attended, Completed, Cancelled, Late cancelled, No-show, Expired.",
        "Cancel booking is not cancel subscription. Booking cancellation never changes the subscription, never creates a booking fee, and never creates a booking refund.",
        "Subscription cancellation is described in the Subscription Terms and does not cancel existing Short Learning bookings before the subscription expires.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "refund-policy",
    slug: "refund-policy",
    title: "Refund Policy",
    category: "legal",
    audience: ["Public","Parent","Platform Admin"],
    purpose: "Clarify when refunds apply for subscriptions and bookings under the locked UK commercial stance.",
    scope: "Subscription payments and Short Learning bookings for the UK launch.",
    summary: "No automatic pro-rata refunds; booking cancel and unused sessions are not refund events; human-tutor unavailability is not a refund event; goodwill refunds are discretionary with audit trail.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/refund-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["subscription-terms","booking-cancellation","ai-use"],
    sections: [
      s("1. Principle",
        "Preferred commercial stance pending solicitor review — not formal legal advice.",
        "StarLiz is a monthly subscription service, not a pay-per-lesson service. Refunds are the exception, not the normal cancellation process.",
        "StarLiz subscriptions provide access to the platform for the duration of the subscription period. Refunds are not normally available for partial use, unused sessions, or voluntary cancellation outside any applicable cooling-off rights. In exceptional circumstances, StarLiz may offer a goodwill refund, account credit, or subscription extension at its discretion.",
      ),
      s("2. No automatic pro-rata refunds",
        "If a parent cancels part-way through a billing period, there is no automatic pro-rata refund.",
        "The subscription remains active until the end of the billing period and access continues until expiry, as described in the Subscription Terms.",
      ),
      s("3. Bookings and unused sessions",
        "Cancelling a Short Learning booking does not create a booking-fee refund because there is no per-booking fee, and there is no late-cancellation charge.",
        "Cancel booking is not cancel subscription and does not change billing.",
        "There is no refund for unused Short Learning sessions. Example: a parent books five sessions, uses none, and cancels the subscription — that unused capacity does not create a refund. The subscription purchased access, not guaranteed attendance.",
      ),
      s("4. Human tutor unavailability",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "No human tutor available does not equal a refund. Where the AI learning service was available and functioning as described, human-tutor unavailability is not a refund event.",
      ),
      s("5. Cooling-off",
        "New consumer online subscriptions have a 14-day cooling-off window as described in the Subscription Terms.",
        "If the parent has not used the digital learning service during that window, a refund can be considered under the final legal wording.",
        "If immediate digital access was chosen and the service has already been used, the final solicitor-approved wording will explain how that affects any cooling-off refund.",
      ),
      s("6. Goodwill refunds (discretionary)",
        "Platform Admin may approve a goodwill refund in exceptional cases. Examples include duplicate payment, billing error, technical issues preventing access for a significant period, accidental duplicate subscription, or exceptional compassionate circumstances.",
        "Goodwill refunds are never automatic.",
        "Authority: Support may recommend only; School Admin cannot approve financial refunds; Platform Admin may approve goodwill refunds; Platform Owner retains final approval for exceptional cases.",
        "Every goodwill refund should record reason, amount, approver, date, notes and an audit log entry through operational billing processes.",
      ),
      s("7. Platform failure remedies",
        "If StarLiz has a significant service failure, Platform Admin may choose to offer a subscription extension, account credit, or goodwill refund.",
        "This policy does not promise a specific automatic remedy; the response depends on the circumstances.",
      ),
      s("8. Payment provider fees",
        "Refunds are handled in accordance with the payment provider's capabilities and this policy. StarLiz does not promise recovery of non-refundable third-party processing fees.",
      ),
      s("9. How to request a review",
        "Contact support@starlizacademy.com with the subscription reference and reason. Support may escalate a recommendation for Platform Admin review.",
      ),
    ],
  }),
  buildPolicy({
    id: "acceptable-use",
    slug: "acceptable-use",
    title: "Acceptable Use Policy",
    category: "legal",
    audience: ["Public","Parent","Student","Tutor"],
    purpose: "Define acceptable and prohibited use of StarLiz Academy.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Define acceptable and prohibited use of StarLiz Academy.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/acceptable-use",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Define acceptable and prohibited use of StarLiz Academy.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Treat learners and staff with respect.",
        "Do not bypass authentication, school scoping or tutor eligibility controls.",
        "Do not claim a named private tutor booking.",
        "Do not share harmful content involving children.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "accessibility",
    slug: "accessibility",
    title: "Accessibility Statement",
    category: "legal",
    audience: ["Public","Parent","School Admin"],
    purpose: "State StarLiz Academy's accessibility target, commitments and support route.",
    scope: "Public website and authenticated portals for the UK launch.",
    summary: "Target WCAG 2.2 Level AA; continuous improvement; support route for barriers — Draft for legal review until independently audited.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/accessibility",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["complaints","terms"],
    sections: [
      s("1. Status",
        "Draft for legal review — not formal legal advice.",
        "Preferred commercial stance pending independent accessibility testing and legal review — not a certification claim.",
        "Target standard: WCAG 2.2 Level AA.",
        "StarLiz is designed with the objective of conforming to WCAG 2.2 Level AA. We continually review and improve accessibility and will address identified accessibility issues as part of our ongoing development programme. This statement is subject to independent accessibility testing and review before final publication.",
      ),
      s("2. What we commit to",
        "Keyboard navigation throughout the platform.",
        "Sufficient colour contrast.",
        "Screen reader compatibility where practical.",
        "Clear heading hierarchy and semantic HTML.",
        "Meaningful labels for forms and controls.",
        "Visible keyboard focus indicators.",
        "Alternative text for informative images.",
        "Captions or transcripts for educational media where applicable.",
        "Avoidance of colour as the only means of conveying information.",
        "Responsive layouts that support zoom and different screen sizes.",
      ),
      s("3. What we do not claim yet",
        "Until independently audited, StarLiz does not claim that it is fully WCAG 2.2 AA compliant, certified accessible, or fully accessible to all users.",
        "This statement describes the target standard and an ongoing commitment to improve accessibility.",
      ),
      s("4. Reporting an accessibility barrier",
        "Email support@starlizacademy.com (or use the published support form) with the page URL and a description of the barrier.",
        "StarLiz will investigate reported accessibility issues and prioritise fixes that block learning, booking or safeguarding reporting.",
        "The Accessibility Statement is reviewed periodically after significant platform changes.",
      ),
      s("5. Related help",
        "For service complaints that are not accessibility barriers, see the Complaints Procedure.",
      ),
    ],
  }),
  buildPolicy({
    id: "complaints",
    slug: "complaints",
    title: "Complaints Procedure",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Explain how to raise a complaint and the published response-time targets.",
    scope: "Service complaints about StarLiz Academy platforms, subscriptions, Short Learning bookings and support. Child welfare concerns follow safeguarding routes, not this SLA table.",
    summary: "How to complain; acknowledge within 2 working days; substantive response within 10; complex within 20; urgent access/payment within 1 — Draft for legal review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/complaints",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["terms","refund-policy","safeguarding","accessibility"],
    sections: [
      s("Purpose and scope",
        "This Complaints Procedure explains how parents and carers can raise a service complaint about StarLiz Academy.",
        "Preferred commercial stance pending solicitor review — published service targets, not guaranteed outcomes or remedies.",
        "It covers platform access, subscriptions, Short Learning bookings, billing administration and customer support quality.",
        "It does not replace school complaints procedures for school-controlled Day School matters, and it does not replace safeguarding reporting.",
      ),
      s("How to raise a complaint",
        "Email support@starlizacademy.com with your account email, a clear description of the issue, and any booking or subscription references.",
        "Accessibility barriers may also be reported under the Accessibility Statement; service complaints that are not accessibility barriers use this procedure.",
        "Booking cancellations remain free of cancellation fees regardless of complaint outcome.",
      ),
      s("Response-time targets",
        "Acknowledge ordinary complaints within 2 working days of receipt.",
        "Provide a substantive response to ordinary complaints within 10 working days of receipt.",
        "Complex or escalated complaints: target a resolution or clear progress update within 20 working days; if still open at day 10, send an interim update.",
        "Urgent account-access or payment-blocking issues that prevent use of a paid service: acknowledge within 1 working day.",
        "Working days means Monday to Friday, excluding UK bank holidays.",
        "These timelines are service targets. They do not guarantee a particular financial outcome, refund, human-tutor assignment, or change to subscription terms.",
      ),
      s("Safeguarding and school routing",
        "Child welfare and safeguarding concerns are outside ordinary complaint SLAs. Email safeguarding@starlizacademy.com immediately, or contact emergency services if there is immediate danger. Do not wait for complaint acknowledgement timelines.",
        "Day School issues that are school-controlled may be referred to the partner school; StarLiz acknowledges receipt and explains routing.",
        "Detailed safeguarding role wording remains subject to focused DSL and legal review in the Safeguarding and Child Protection Policy.",
      ),
      s("Escalation",
        "Unresolved complaints may be escalated from Support to Platform Admin.",
        "Support may recommend goodwill or other remedies where relevant; financial refund decisions follow the Refund Policy and remain Platform Admin / Owner discretion where applicable.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "intellectual-property",
    slug: "intellectual-property",
    title: "Intellectual Property Policy",
    category: "legal",
    audience: ["Public","Parent"],
    purpose: "Describe ownership of platform content and limits on reuse.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Describe ownership of platform content and limits on reuse.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/intellectual-property",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Describe ownership of platform content and limits on reuse.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Platform software, branding and curriculum structures are protected IP.",
        "Users receive a limited licence for intended learning use.",
        "Do not commercially exploit platform content without permission.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "ai-use",
    slug: "ai-use",
    title: "AI Use and Transparency Policy",
    category: "legal",
    audience: ["Public","Parent","Student"],
    purpose: "Explain how AI is used in teaching.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Explain how AI is used in teaching.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/ai-use",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Explain how AI is used in teaching.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "AI teaches and adapts practice during sessions.",
        "AI does not guarantee a human tutor will join and does not create a private named-tutor reservation.",
        "If no tutor is available, the child continues with AI.",
        "For school-directed Day School AI delivery under school instructions, the school is normally controller and StarLiz is processor. For direct Short Learning and for StarLiz platform AI safety/security processing, StarLiz is normally controller. See the Data Protection Policy.",
        "Report AI concerns to support@starlizacademy.com.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "online-safety",
    slug: "online-safety",
    title: "Online Safety Policy",
    category: "legal",
    audience: ["Public","Parent","Student","Tutor"],
    purpose: "Describe online safety expectations for digital learning.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Describe online safety expectations for digital learning.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/online-safety",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Describe online safety expectations for digital learning.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Children should use the platform with suitable adult oversight for their age.",
        "Report inappropriate content to support@starlizacademy.com or safeguarding@starlizacademy.com.",
        "Human support is for learning help within an active session.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "safeguarding",
    slug: "safeguarding",
    title: "Safeguarding and Child Protection Policy",
    category: "legal",
    audience: ["Public","Parent","Tutor","School Admin","Staff"],
    purpose: "Public summary of child welfare commitments, roles and reporting routes.",
    scope: "Children using StarLiz Academy; staff and tutors interacting with learners.",
    summary: "Child safety first; school-directed vs StarLiz-independent safeguarding roles; reporting routes — draft for DSL and legal review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/safeguarding-policy",
    reportingRoute: "safeguarding@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["data-protection","online-safety","human-tutor-support"],
    sections: [
      s("1. Commitment",
        "The welfare of the child is paramount. This public policy summarises commitments and is a draft for DSL and legal review.",
        "It is not a full statutory safeguarding manual for partner schools.",
      ),
      s("2. Controller roles for safeguarding information",
        "Preferred data-governance position pending solicitor and DPO review.",
        "For routine school-directed safeguarding records, the school normally remains controller and StarLiz acts as processor.",
        "Where StarLiz independently decides that it must record, preserve or disclose information to protect a child, comply with law, manage an incident or cooperate with authorities, StarLiz may act as an independent controller for that specific processing.",
        "Safeguarding disclosures must be limited, documented and routed through authorised safeguarding personnel.",
      ),
      s("3. Product controls",
        "Role-based portals, school scoping, and support eligibility controls limit who can interact with learners.",
        "Human tutors must be on shift with fresh presence to accept support work.",
        "Safeguarding incident workflows exist for authorised staff in the platform where enabled.",
      ),
      s("4. Reporting concerns",
        "Immediate danger: contact emergency services first.",
        "Then notify safeguarding@starlizacademy.com and, where relevant, the child's school DSL.",
        "Parents may also contact support@starlizacademy.com for non-emergency welfare concerns.",
      ),
      s("5. Records",
        "Safeguarding records are handled under restricted access and the Data Retention Policy's safeguarding carve-out (no short automatic deletion).",
      ),
    ],
  }),
  buildPolicy({
    id: "data-protection",
    slug: "data-protection",
    title: "Data Protection Policy",
    category: "legal",
    audience: ["Public","School Admin","Platform Admin","Staff"],
    purpose: "Set organisational data protection principles and the preferred controller/processor mapping by processing purpose.",
    scope: "Staff and processors handling personal data for StarLiz Academy UK launch services, including school and direct-to-parent arrangements.",
    summary: "Role-by-purpose controller/processor mapping, Article 28 DPA expectations, rights-request routing, retention link — preferred governance position pending solicitor/DPO review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/data-protection",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["privacy","data-retention","safeguarding","ai-use"],
    sections: [
      s("1. Status and principles",
        "Preferred data-governance position pending solicitor and DPO review — not formal legal advice.",
        "Process personal data under UK GDPR principles. Children's data is kept to the minimum necessary.",
        "StarLiz uses a role-by-processing-purpose model. An organisation can be a processor for some activities and a controller for others, depending on who decides the purpose and essential means of processing.",
      ),
      s("2. Day School records",
        "For school-provisioned Day School activity, the school or academy trust is data controller and StarLiz is data processor.",
        "This covers school enrolment and classroom membership; fixed timetable records; attendance registers; teacher-assigned lessons; school-directed learning records; school reports; classroom and tutor assignments; school-configured safeguarding workflows; and school-authorised exports.",
        "The school determines why these records are processed. StarLiz processes them to provide the contracted service under documented instructions.",
        "School agreements must include an Article 28-compliant Data Processing Agreement covering security, sub-processors, deletion or return, breach notification, staff access, rights assistance, transfers, safeguarding escalation and end-of-contract export/deletion.",
      ),
      s("3. Direct-to-parent Short Learning",
        "For subscriptions purchased directly by a parent, StarLiz is data controller for parent and student account creation; subscription and billing administration; Short Learning bookings; entitlement checks; booking reliability and no-show controls; direct customer communications; direct-to-parent reports; service improvement necessary to operate Short Learning; complaints and customer support; and fraud, security and audit records for that service.",
      ),
      s("4. School-funded Short Learning",
        "Where a school purchases Short Learning for pupils, roles are assessed by purpose rather than assumed.",
        "Preferred default: school-directed pupil participation and educational use — school controller, StarLiz processor; StarLiz's independent billing, platform security, fraud prevention and legal compliance processing — StarLiz controller.",
        "This is a split-role arrangement by processing activity, not automatically joint controllership.",
      ),
      s("5. AI Tutor and analytics",
        "School-directed Day School AI processing used solely to deliver the school's selected lesson and return results under school instructions: school controller, StarLiz processor.",
        "StarLiz-controlled AI safety and platform operation (security, abuse detection, integrity, legal compliance, AI safety incidents, claims defence, operational audit): StarLiz controller.",
        "Do not use the processor role as permission to reuse school pupil data for unrelated model training, advertising or broad product experimentation.",
        "Identifiable school pupil data is not used for StarLiz independent product development unless the school contract expressly permits the specific processing, the role and lawful basis are documented, transparency is provided, and a DPIA supports the use where required.",
        "Irreversibly anonymised analytics may be used for capacity planning, performance, quality monitoring, aggregate educational insight and product improvement. Pseudonymised data remains personal data and must not be described as anonymous.",
      ),
      s("6. Human tutor support",
        "Day School human-support cases: school controller, StarLiz processor.",
        "Short Learning human-support cases bought directly by parents: StarLiz controller.",
        "Tutor staff and contractors act under the authority of the relevant controller/processor arrangement. They are not independent controllers merely because they view or create session notes.",
      ),
      s("7. Safeguarding",
        "For routine school-directed safeguarding records, the school normally remains controller and StarLiz acts as processor.",
        "Where StarLiz independently decides that it must record, preserve or disclose information to protect a child, comply with law, manage an incident or cooperate with authorities, StarLiz may act as an independent controller for that specific processing.",
      ),
      s("8. Platform administration, security and suppliers",
        "StarLiz is controller for staff accounts used to operate StarLiz; authentication and access logs; platform audit logs; cybersecurity monitoring; fraud and misuse prevention; provider management; legal compliance; incident investigation; and service availability monitoring.",
        "Payment providers and infrastructure suppliers are described according to the real contract as processor, independent controller or, exceptionally, joint controller — not automatically all processors.",
        "StarLiz maintains a current sub-processor register, written processor terms, international-transfer safeguards where required, prior authorisation mechanisms for school-controlled data, and equivalent protections in downstream processor contracts.",
      ),
      s("9. Rights-request routing",
        "Day School / school-controlled request: StarLiz receives the request, logs it, verifies enough information to route safely, promptly refers it to the school, and assists the school under the DPA. StarLiz must not independently decide the school's response unless legally required.",
        "Direct Short Learning / StarLiz-controlled request: StarLiz handles the request directly.",
        "Mixed request: split internally and explain clearly which organisation is handling each part.",
      ),
      s("10. Retention and breaches",
        "Retention periods follow the Data Retention Policy, including school-instruction priority for school-controlled records.",
        "Suspected breaches must be reported internally immediately for assessment against UK GDPR notification duties and any contractual notice requirements to schools.",
      ),
      s("11. Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "data-retention",
    slug: "data-retention",
    title: "Data Retention Policy",
    category: "legal",
    audience: ["Public","Parent","School Admin","Staff","Platform Admin"],
    purpose: "Document StarLiz Academy's commercial retention schedule and deletion approach pending solicitor and DPO review.",
    scope: "Account, learning, booking, support, financial, security, HR-adjacent and safeguarding-related records processed in the UK launch scope.",
    summary: "Commercial retention schedule with school-instruction priority, safeguarding carve-out, deletion/anonymisation approach and operational controls — pending solicitor/DPO review.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/data-retention",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    relatedDocumentIds: ["privacy","data-protection","safeguarding","subscription-terms"],
    sections: [
      s("1. Status and principles",
        "Commercial retention schedule pending solicitor and DPO review — not formal legal advice.",
        "UK GDPR does not prescribe one universal retention period. StarLiz must justify each period, document it, review it regularly, and delete or anonymise data once it is no longer needed. Children's data should be kept to the minimum necessary.",
        "At the end of each period: delete identifiable data, or irreversibly anonymise it where aggregate analysis remains useful. Properly anonymised information falls outside data-protection law because individuals are no longer identifiable.",
        "Legal hold, safeguarding need, fraud investigation, active complaint or litigation pauses normal deletion only for the affected records.",
      ),
      s("2. School-controlled records",
        "Where StarLiz processes records on behalf of a school, the school's approved retention schedule and documented instructions take priority, subject to applicable law. StarLiz will not independently shorten or extend those periods without authority.",
        "Day School attendance and lesson records where StarLiz is acting for a school follow the school's documented schedule; StarLiz does not independently delete those records without school instruction.",
        "Guidance that certain official school pupil records may be retained until a pupil's 25th birthday does not mean every StarLiz learning interaction is automatically kept that long. Applicability depends on whether StarLiz holds the official education record, acts as the school's processor, or operates a direct-to-parent service — to be confirmed in controller mapping.",
      ),
      s("3. Account and profile records",
        "Active parent, student and staff account data: while account or access remains active.",
        "Closed parent account profile: 24 months after closure.",
        "Closed student profile and ordinary learning preferences: 24 months after closure or school relationship ends.",
      ),
      s("4. Learning, bookings and support",
        "Short Learning bookings and attendance states: 3 years after the session.",
        "Learning attempts, stages, progress and reports: 3 years after the last learning activity.",
        "Detailed AI Tutor conversations: 12 months after the session. AI help analytics with identifiers removed may be retained longer in genuinely anonymised form.",
        "Human-support session notes and outcomes: 3 years after the session.",
        "Tutor presence, heartbeat and operational shift logs: 12 months. Tutor shifts and capacity records: 3 years.",
        "Booking cancellations, late cancellations and no-show history: 24 months. Reliability restrictions and related decisions: restriction duration plus 12 months.",
      ),
      s("5. Agreements, billing and support cases",
        "Parent honesty acknowledgements and accepted policy versions: 6 years after the relevant subscription or booking relationship ends.",
        "Subscription, invoices, payments, refunds and financial audit records: 6 years from the end of the relevant financial year.",
        "Customer-support enquiries and complaints: 3 years after closure. Serious complaints or threatened or legal claims: 6 years after final resolution.",
        "Consent and marketing preference records: while active, then 3 years after withdrawal or last interaction. Cookie consent evidence: 24 months, then refresh or remove.",
      ),
      s("6. Security, audit and backups",
        "Routine security and application logs: 12 months. High-risk security incident and breach records: 6 years after closure.",
        "Admin audit logs involving access, bookings, shifts and policy actions: 6 years. Failed login and abuse-prevention records: 12 months, shorter where practical.",
        "Deleted-account backups: removed through normal backup rotation within 90 days.",
      ),
      s("7. HR-adjacent and safeguarding",
        "Job applications for unsuccessful candidates: 6 months after recruitment closes.",
        "Staff employment and payroll records: separate HR schedule; payroll records at least the legally required period.",
        "Safeguarding records: do not apply a short automatic deletion period; retain under the safeguarding schedule and controller instructions, with regular necessity review. Focused legal and DSL review required before any fixed safeguarding period is published as Approved.",
      ),
      s("8. Retention operations",
        "Internal operations should maintain a documented retention register; automate deletion or anonymisation where practical; review every retention category annually; keep deletion logs; handle backup expiry; apply legal-hold controls; and treat direct-to-parent and school-controlled records separately.",
        "This Phase 6 document locks the commercial schedule in policy. It does not by itself implement automated purge jobs.",
      ),
      s("9. Requests",
        "Deletion or access requests: support@starlizacademy.com. Safeguarding and legal holds may limit erasure for affected records.",
      ),
    ],
  }),
  buildPolicy({
    id: "account-suspension",
    slug: "account-suspension",
    title: "Account Suspension and Termination Policy",
    category: "legal",
    audience: ["Public","Parent","Tutor","School Admin"],
    purpose: "Explain when accounts may be restricted or terminated.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Explain when accounts may be restricted or terminated.",
    legalReviewRequired: true,
    status: "Draft",
    publicVisible: true,
    publicPath: "/policies/account-suspension",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Explain when accounts may be restricted or terminated.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Grounds include Acceptable Use breaches, safeguarding risk, booking abuse after reliability controls, and failed payment after the 7-day grace period described in the Subscription Terms.",
        "Appeals: support@starlizacademy.com.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  })
];
