import { buildPolicy, s } from "../build";
import type { PolicyDocument } from "../types";

/** Phase 6 draft set — aligned to shipped product behaviour. */
export const PRODUCT_POLICIES: PolicyDocument[] = [
  buildPolicy({
    id: "short-learning-policy",
    slug: "short-learning-policy",
    title: "Short Learning Policy",
    category: "product",
    audience: ["Public","Parent","School Admin"],
    purpose: "Define Short Learning as parent-booked AI-led after-hours learning.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Define Short Learning as parent-booked AI-led after-hours learning.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/short-learning-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Define Short Learning as parent-booked AI-led after-hours learning.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Short Learning is parent-booked learning time outside Day School hours.",
        "Sessions are AI-led and are not named-tutor bookings.",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Session lengths are 90 or 120 minutes, starting every 30 minutes where capacity permits.",
        "Weekday window: 16:00–20:00. Weekend window: 09:00–18:00.",
        "Short Learning bookings use published after-hours capacity windows.",
        "Weekday bookings open 7 days ahead. Standard deadline: 12:00 same day. School admin finalises tutor shifts by 14:00. Late booking is allowed only where existing capacity permits. Free cancellation until 2 hours before the session.",
        "Weekend bookings open 14 days ahead. Standard deadline: Thursday 18:00. School admin finalises tutor shifts by Friday 12:00. Late booking only where capacity permits. Free cancellation until 18:00 the previous day.",
        "There is no per-booking fee, no cancellation fee, no late-cancellation charge, and no private-tutor fee. The monthly subscription covers Short Learning access.",
        "Cancellations and no-shows affect operations and reliability tracking only. They are not financial penalties.",
        "Booking statuses include: Booked, Confirmed, Attended, Completed, Cancelled, Late cancelled, No-show, Expired.",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "day-school-policy",
    slug: "day-school-policy",
    title: "Day School Learning Policy",
    category: "product",
    audience: ["Public","Parent","School Admin","Tutor"],
    purpose: "Define Day School as timetabled school-day learning separate from Short Learning.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Define Day School as timetabled school-day learning separate from Short Learning.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/day-school-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Define Day School as timetabled school-day learning separate from Short Learning.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Day School follows a fixed school timetable with school-led attendance.",
        "Day School is teacher-led and AI-first during the school day.",
        "Parents do not book Day School periods.",
        "Day School uses school timetable lesson records and must not be confused with Short Learning bookings.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "human-tutor-support",
    slug: "human-tutor-support",
    title: "Human Tutor Support Policy",
    category: "product",
    audience: ["Public","Parent","Tutor","School Admin"],
    purpose: "Define human support as a non-guaranteed safety net.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Define human support as a non-guaranteed safety net.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/human-tutor-support",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Define human support as a non-guaranteed safety net.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "ai-tutor-policy",
    slug: "ai-tutor-policy",
    title: "AI Tutor Policy",
    category: "product",
    audience: ["Public","Parent","Student"],
    purpose: "Describe AI Tutor teaching behaviour and limits.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Describe AI Tutor teaching behaviour and limits.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/ai-tutor-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Describe AI Tutor teaching behaviour and limits.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "AI leads Short Learning sessions and continues when human support is unavailable.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "parent-responsibilities",
    slug: "parent-responsibilities",
    title: "Parent Responsibilities Policy",
    category: "product",
    audience: ["Parent"],
    purpose: "Set expectations for parents.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Set expectations for parents.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/parent-responsibilities",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Set expectations for parents.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Keep child profiles accurate.",
        "Book only when the child can attend.",
        "Cancel when plans change — there is no cancellation fee.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "student-code",
    slug: "student-code",
    title: "Student Code of Conduct",
    category: "product",
    audience: ["Student","Parent"],
    purpose: "Expected student behaviour.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Expected student behaviour.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/student-code",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Expected student behaviour.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Be kind and try your best.",
        "Ask the AI Tutor for help when stuck.",
        "Tell a trusted adult if something feels wrong.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "tutor-code",
    slug: "tutor-code",
    title: "Tutor Code of Conduct",
    category: "product",
    audience: ["Tutor","School Admin"],
    purpose: "Professional expectations for tutors.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Professional expectations for tutors.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/tutor-code",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Professional expectations for tutors.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Follow safeguarding rules.",
        "Only go available on published shifts with fresh presence.",
        "Do not imply a private named booking.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "attendance-policy",
    slug: "attendance-policy",
    title: "Attendance Policy",
    category: "product",
    audience: ["Parent","School Admin","Tutor"],
    purpose: "Attendance for Day School vs Short Learning.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Attendance for Day School vs Short Learning.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/attendance-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Attendance for Day School vs Short Learning.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Day School attendance is school-led.",
        "Short Learning attendance uses Short Learning booking statuses.",
        "Do not merge the two.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "booking-reliability",
    slug: "booking-reliability",
    title: "Booking Reliability and No-Show Policy",
    category: "product",
    audience: ["Parent","School Admin"],
    purpose: "Reliability controls without financial penalties.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Reliability controls without financial penalties.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/booking-reliability",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Reliability controls without financial penalties.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "No-shows may reduce limits or require confirmations — not fees.",
        "There is no cancellation fee.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "behaviour-policy",
    slug: "behaviour-policy",
    title: "Behaviour Policy",
    category: "product",
    audience: ["Parent","Student","Tutor","School Admin"],
    purpose: "Behaviour expectations.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Behaviour expectations.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/behaviour-policy",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Behaviour expectations.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Respectful conduct required in AI and human-supported sessions.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "assessment-progress",
    slug: "assessment-progress",
    title: "Assessment and Progress Policy",
    category: "product",
    audience: ["Parent","School Admin"],
    purpose: "How progress is tracked.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "How progress is tracked.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/assessment-progress",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "How progress is tracked.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Progress may come from lessons, assessments and Short Learning activity.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "learning-reports",
    slug: "learning-reports",
    title: "Learning Reports Policy",
    category: "product",
    audience: ["Parent","School Admin"],
    purpose: "Who can see learning reports.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Who can see learning reports.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/learning-reports",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Who can see learning reports.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Parents see linked children; school staff see school-scoped learners.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "lesson-quality",
    slug: "lesson-quality",
    title: "Lesson Quality Policy",
    category: "product",
    audience: ["School Admin","Platform Admin","Staff"],
    purpose: "Quality expectations.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Quality expectations.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/lesson-quality",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Quality expectations.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Lessons should be age-appropriate and safe.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "content-review",
    slug: "content-review",
    title: "Content Review Policy",
    category: "product",
    audience: ["Platform Admin","Staff"],
    purpose: "How content is reviewed.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "How content is reviewed.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/content-review",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "How content is reviewed.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Review for accuracy, safeguarding and age suitability.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "ai-safety",
    slug: "ai-safety",
    title: "AI Safety Policy",
    category: "product",
    audience: ["Parent","Staff","Platform Admin"],
    purpose: "Safety controls around AI.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Safety controls around AI.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/ai-safety",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Safety controls around AI.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Report unsafe AI behaviour to support.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "human-support-escalation",
    slug: "human-support-escalation",
    title: "Human Support Escalation Policy",
    category: "product",
    audience: ["Tutor","School Admin","Staff"],
    purpose: "Escalation paths.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Escalation paths.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/human-support-escalation",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Escalation paths.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Learning stuck paths may reach on-shift tutors when eligible.",
        "Welfare concerns use safeguarding procedures.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "tutor-availability-shifts",
    slug: "tutor-availability-shifts",
    title: "Tutor Availability and Shift Policy",
    category: "product",
    audience: ["Tutor","School Admin"],
    purpose: "Shifts gate availability.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Shifts gate availability.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/tutor-availability-shifts",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Shifts gate availability.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "incident-reporting",
    slug: "incident-reporting",
    title: "Incident Reporting Policy",
    category: "product",
    audience: ["Tutor","School Admin","Staff","Parent"],
    purpose: "How to report incidents.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "How to report incidents.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/incident-reporting",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "How to report incidents.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Technical: support@starlizacademy.com. Safeguarding: safeguarding channels.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "quality-assurance",
    slug: "quality-assurance",
    title: "Quality Assurance Policy",
    category: "product",
    audience: ["School Admin","Platform Admin","Staff"],
    purpose: "QA across learning and support.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "QA across learning and support.",
    legalReviewRequired: false,
    status: "Under Review",
    publicVisible: true,
    publicPath: "/policies/quality-assurance",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "QA across learning and support.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Monitor reliability, shift coverage, AI quality and safeguarding workflows.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  })
];
