import { buildPolicy, s } from "../build";
import type { PolicyDocument } from "../types";

/** Phase 6 draft set — aligned to shipped product behaviour. */
export const STAFF_DOCS: PolicyDocument[] = [
  buildPolicy({
    id: "tutor-handbook",
    slug: "tutor-handbook",
    title: "Tutor Handbook",
    category: "handbook",
    audience: ["Tutor","Staff"],
    purpose: "Practical guide for tutors.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Practical guide for tutors.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/tutor-handbook",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Practical guide for tutors.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
        "Use teacher portal tools. Off-shift: upcoming shifts and history only.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "school-admin-ops",
    slug: "school-admin-ops",
    title: "School Admin Operations Manual",
    category: "handbook",
    audience: ["School Admin"],
    purpose: "Operate from /school-admin.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Operate from /school-admin.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/school-admin-ops",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Operate from /school-admin.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Short Learning tabs cover bookings, forecast, shifts, coverage, policies and reliability.",
        "Day School attendance stays separate.",
        "Finalise weekday shifts by 14:00 and weekend shifts by Friday 12:00 where process requires.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "platform-admin-ops",
    slug: "platform-admin-ops",
    title: "Platform Super Admin Operations Manual",
    category: "handbook",
    audience: ["Platform Admin"],
    purpose: "Operate from /admin.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Operate from /admin.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/platform-admin-ops",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Operate from /admin.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Use Short Learning oversight.",
        "Never migrate reset production.",
        "Set CRON_SECRET and provider keys in Vercel Production.",
        "Complaint response-time targets (service targets, not guaranteed remedies): acknowledge ordinary complaints within 2 working days; substantive response within 10; complex/escalated within 20 with interim update by day 10 if still open; urgent access/payment-blocking within 1 working day. Escalate unresolved cases from Support to Platform Admin. Safeguarding is outside these SLAs.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "human-support-runbook",
    slug: "human-support-runbook",
    title: "Human Support Operations Runbook",
    category: "runbook",
    audience: ["Tutor","School Admin","Staff"],
    purpose: "Operate the human support safety net.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Operate the human support safety net.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/human-support-runbook",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Operate the human support safety net.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "safeguarding-escalation",
    slug: "safeguarding-escalation",
    title: "Safeguarding Escalation Procedure",
    category: "runbook",
    audience: ["Staff","School Admin","Tutor"],
    purpose: "Escalate welfare concerns.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Escalate welfare concerns.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/safeguarding-escalation",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Escalate welfare concerns.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Protect the child first.",
        "Notify school DSL and safeguarding@starlizacademy.com.",
        "Do not use the tutor queue as safeguarding.",
        "Child welfare concerns are outside ordinary complaint response-time SLAs — escalate immediately; do not wait for the 2-working-day acknowledgement target used for service complaints.",
        "Detailed public safeguarding role wording remains pending focused DSL and legal review.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "incident-response",
    slug: "incident-response",
    title: "Incident Response Procedure",
    category: "runbook",
    audience: ["Platform Admin","Staff"],
    purpose: "Respond to production incidents.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Respond to production incidents.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/incident-response",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Respond to production incidents.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Contain, communicate, remediate, review. See docs/ops runbooks.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "ai-monitoring",
    slug: "ai-monitoring",
    title: "AI Monitoring Procedure",
    category: "runbook",
    audience: ["Platform Admin","Staff"],
    purpose: "Monitor AI tutoring.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Monitor AI tutoring.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/ai-monitoring",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Monitor AI tutoring.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Review quality signals and reported concerns.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "booking-capacity-guide",
    slug: "booking-capacity-guide",
    title: "Booking and Capacity Planning Guide",
    category: "handbook",
    audience: ["School Admin"],
    purpose: "Plan Short Learning capacity.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Plan Short Learning capacity.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/booking-capacity-guide",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Plan Short Learning capacity.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Weekday bookings open 7 days ahead. Standard deadline: 12:00 same day. School admin finalises tutor shifts by 14:00. Late booking is allowed only where existing capacity permits. Free cancellation until 2 hours before the session.",
        "Weekend bookings open 14 days ahead. Standard deadline: Thursday 18:00. School admin finalises tutor shifts by Friday 12:00. Late booking only where capacity permits. Free cancellation until 18:00 the previous day.",
        "There is no per-booking fee, no cancellation fee, no late-cancellation charge, and no private-tutor fee. The monthly subscription covers Short Learning access.",
        "Cancellations and no-shows affect operations and reliability tracking only. They are not financial penalties.",
        "Booking statuses include: Booked, Confirmed, Attended, Completed, Cancelled, Late cancelled, No-show, Expired.",
        "Late booking only when capacity remains.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "tutor-shift-guide",
    slug: "tutor-shift-guide",
    title: "Tutor Shift Scheduling Guide",
    category: "handbook",
    audience: ["School Admin","Tutor"],
    purpose: "Publish and manage shifts.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Publish and manage shifts.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/tutor-shift-guide",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Publish and manage shifts.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "AI teaching is guaranteed. Human support is a safety net when available — not a private 1:1 tutor booking.",
        "Human tutor support is only considered when AI support is exhausted, the student still needs help, the learning session is active, an eligible tutor is on shift, the tutor is available, the heartbeat is fresh, and tutor access is active.",
        "If no tutor is available, the child continues with AI and is not parked waiting for an offline tutor. Human support is not guaranteed.",
        "Login does not mean available. A tutor can only become available when on shift, heartbeat is fresh, and access is active.",
        "Outside shift, tutors may access dashboard, upcoming shifts, notices and history. They cannot become available, accept a student, claim a support case, or receive a new assignment.",
        "At shift end: no new assignments. An active session may finish within the configured grace period. Then the tutor returns off shift.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "reminder-ops",
    slug: "reminder-ops",
    title: "Production Reminder Operations Guide",
    category: "runbook",
    audience: ["Platform Admin","Staff"],
    purpose: "Operate reminders.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Operate reminders.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/reminder-ops",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Operate reminders.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "Endpoint /api/cron/short-learning-reminders",
        "Vercel Cron */10 * * * *",
        "Auth: CRON_SECRET Bearer header",
        "Do not publish the secret publicly.",
        "Requires Pro+ and email provider credentials.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  }),
  buildPolicy({
    id: "policy-review-procedure",
    slug: "policy-review-procedure",
    title: "Policy Review and Approval Procedure",
    category: "handbook",
    audience: ["Platform Admin","Staff"],
    purpose: "Policy lifecycle.",
    scope: "StarLiz Academy UK launch product behaviour as implemented.",
    summary: "Policy lifecycle.",
    legalReviewRequired: false,
    status: "Draft",
    publicVisible: false,
    publicPath: "/policies/policy-review-procedure",
    reportingRoute: "support@starlizacademy.com",
    complaintsRoute: "support@starlizacademy.com",
    
    
    
    
    sections: [
      s("Purpose and scope",
        "Policy lifecycle.",
        "This document reflects shipped behaviour and is subject to review.",
      ),
      s("Policy rules",
        "States: Draft, Under Review, Approved, Published, Archived.",
        "Legal policies need external legal review before formal approval claims.",
        "Do not invent solicitor approvals.",
      ),
      s("Reporting",
        "Contact support@starlizacademy.com. For child welfare concerns use safeguarding@starlizacademy.com.",
      ),
    ],
  })
];
